/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.witsml1_4_1_1;

		import com.f2i.energisticsStandardsApi.*;
	
public class Log extends com.f2i.energisticsStandardsApi.witsml1_4_1_1.AbstractObject {
  private long swigCPtr;

  public Log(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Log obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_witsml1_4_1_1_Log(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public witsml1__LogIndexType getIndexType() {
    return witsml1__LogIndexType.swigToEnum(com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_getIndexType(swigCPtr, this));
  }

  public String getIndexMnemonic() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_getIndexMnemonic(swigCPtr, this);
  }

  public StringVector getData() {
    return new StringVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_getData(swigCPtr, this), false);
  }

  public StringVector getMnemonicSet() {
    return new StringVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_getMnemonicSet(swigCPtr, this), true);
  }

  public void setValues(String description, String dataDelimiter, String startEndIncrementUOM, double startIndex, double endIndex, double stepIncrement, witsml1__LogIndexDirection direction, String mnemonicList, String unitList, StringVector data) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_setValues(swigCPtr, this, description, dataDelimiter, startEndIncrementUOM, startIndex, endIndex, stepIncrement, direction.swigValue(), mnemonicList, unitList, StringVector.getCPtr(data), data);
  }

  public long getLogCurveCount() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_getLogCurveCount(swigCPtr, this);
  }

  public String getLogCurveMnemonic(long logCurveIndex) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_getLogCurveMnemonic(swigCPtr, this, logCurveIndex);
  }

  public witsml1__LogDataType getLogCurveDataType(long logCurveIndex) {
    return witsml1__LogDataType.swigToEnum(com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_getLogCurveDataType(swigCPtr, this, logCurveIndex));
  }

  public String getLogCurveUom(long logCurveIndex) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_getLogCurveUom(swigCPtr, this, logCurveIndex);
  }

  public void pushBackLogCurveInfo(String mnemonic, witsml1__LogDataType typeLogData) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_pushBackLogCurveInfo__SWIG_0(swigCPtr, this, mnemonic, typeLogData.swigValue());
  }

  public void pushBackLogCurveInfo(String namingSystem, String mnemonic, String classWitsml, String unit, int datumIndex, String minMaxIndexUOM, double minIndex, double maxIndex, String curveDescription, witsml1__PerLengthUom perLengthUOM, double densData, witsml1__LogTraceOrigin traceOrigin, witsml1__LogDataType typeLogData) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_pushBackLogCurveInfo__SWIG_1(swigCPtr, this, namingSystem, mnemonic, classWitsml, unit, datumIndex, minMaxIndexUOM, minIndex, maxIndex, curveDescription, perLengthUOM.swigValue(), densData, traceOrigin.swigValue(), typeLogData.swigValue());
  }

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.Wellbore getWellbore() {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_getWellbore(swigCPtr, this);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.witsml1_4_1_1.Wellbore(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.WellboreFrameRepresentation getResqmlWellboreFrameRepresentation() {
		long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Log_getResqmlWellboreFrameRepresentation(swigCPtr, this);
		com.f2i.energisticsStandardsApi.resqml2_0.WellboreFrameRepresentation ret = (com.f2i.energisticsStandardsApi.resqml2_0.WellboreFrameRepresentation) energisticsApiJNI.resqml2_0_instantiateWellboreFrameRepresentationObject(cPtr, false);
		return ret;
	}

}
