/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.witsml1_4_1_1;

		import com.f2i.energisticsStandardsApi.*;
	
public class Wellbore extends com.f2i.energisticsStandardsApi.witsml1_4_1_1.AbstractObject {
  private long swigCPtr;

  public Wellbore(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Wellbore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_witsml1_4_1_1_Wellbore(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.Trajectory createTrajectory(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_createTrajectory__SWIG_0(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.witsml1_4_1_1.Trajectory(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.Trajectory createTrajectory(String guid, String title, String sourceName, long dTimCreation, long dTimLastChange, String comments) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_createTrajectory__SWIG_1(swigCPtr, this, guid, title, sourceName, dTimCreation, dTimLastChange, comments);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.witsml1_4_1_1.Trajectory(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.Log createLog(String guid, String title, witsml1__LogIndexType indexType, String indexCurve) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_createLog__SWIG_0(swigCPtr, this, guid, title, indexType.swigValue(), indexCurve);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.witsml1_4_1_1.Log(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.Log createLog(String guid, String title, witsml1__LogIndexType indexType, String indexCurve, String sourceName, long dTimCreation, long dTimLastChange, String comments) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_createLog__SWIG_1(swigCPtr, this, guid, title, indexType.swigValue(), indexCurve, sourceName, dTimCreation, dTimLastChange, comments);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.witsml1_4_1_1.Log(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.FormationMarker createFormationMarker(String guid, String title, long mdDatumIndex, witsml1__MeasuredDepthUom mdUom, double mdTopSample) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_createFormationMarker__SWIG_0(swigCPtr, this, guid, title, mdDatumIndex, mdUom.swigValue(), mdTopSample);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.witsml1_4_1_1.FormationMarker(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.FormationMarker createFormationMarker(String guid, String title, long mdDatumIndex, witsml1__MeasuredDepthUom mdUom, double mdTopSample, long tvdDatumIndex, witsml1__WellVerticalCoordinateUom tvdUom, double tvdTopSample, witsml1__PlaneAngleUom dipUom, double dip, witsml1__PlaneAngleUom dipDirectionUom, double dipDirection, String sourceName, long dTimCreation, long dTimLastChange, String comments) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_createFormationMarker__SWIG_1(swigCPtr, this, guid, title, mdDatumIndex, mdUom.swigValue(), mdTopSample, tvdDatumIndex, tvdUom.swigValue(), tvdTopSample, dipUom.swigValue(), dip, dipDirectionUom.swigValue(), dipDirection, sourceName, dTimCreation, dTimLastChange, comments);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.witsml1_4_1_1.FormationMarker(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.Well getWell() {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_getWell(swigCPtr, this);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.witsml1_4_1_1.Well(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.WellboreFeature getResqmlWellboreFeature() {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_getResqmlWellboreFeature(swigCPtr, this);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.WellboreFeature(cPtr, false);
  }

  public TrajectoryVector getTrajectories() {
    return new TrajectoryVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_getTrajectories(swigCPtr, this), false);
  }

  public LogVector getLogs() {
    return new LogVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_getLogs(swigCPtr, this), false);
  }

  public FormationMarkerVector getFormationMarkers() {
    return new FormationMarkerVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_getFormationMarkers(swigCPtr, this), false);
  }

  public void setShape(witsml1__WellboreShape shape) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.witsml1_4_1_1_Wellbore_setShape(swigCPtr, this, shape.swigValue());
  }

}
