//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace f2i.energisticsStandardsApi.resqml2_0 {

public class AbstractFeatureInterpretation : f2i.energisticsStandardsApi.resqml2_0.AbstractResqmlDataObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal AbstractFeatureInterpretation(global::System.IntPtr cPtr, bool cMemoryOwn) : base(f2i.energisticsStandardsApi.energisticsApiPINVOKE.resqml2_0_AbstractFeatureInterpretation_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AbstractFeatureInterpretation obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AbstractFeatureInterpretation() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          f2i.energisticsStandardsApi.energisticsApiPINVOKE.delete_resqml2_0_AbstractFeatureInterpretation(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public uint getRepresentationCount() {
    uint ret = f2i.energisticsStandardsApi.energisticsApiPINVOKE.resqml2_0_AbstractFeatureInterpretation_getRepresentationCount(swigCPtr);
    if (f2i.energisticsStandardsApi.energisticsApiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.energisticsApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public f2i.energisticsStandardsApi.resqml2_0.AbstractFeature getInterpretedFeature() {
		global::System.IntPtr cPtr = f2i.energisticsStandardsApi.energisticsApiPINVOKE.resqml2_0_AbstractFeatureInterpretation_getInterpretedFeature(swigCPtr);
		f2i.energisticsStandardsApi.resqml2_0.AbstractFeature ret = (f2i.energisticsStandardsApi.resqml2_0.AbstractFeature) energisticsApiPINVOKE.resqml2_0_instantiateConcreteObject(cPtr, false);
    if (f2i.energisticsStandardsApi.energisticsApiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.energisticsApiPINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation getRepresentation(uint index) {
		global::System.IntPtr cPtr = f2i.energisticsStandardsApi.energisticsApiPINVOKE.resqml2_0_AbstractFeatureInterpretation_getRepresentation(swigCPtr, index);
		f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation ret = (f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation) energisticsApiPINVOKE.resqml2_0_instantiateConcreteObject(cPtr, false);
    if (f2i.energisticsStandardsApi.energisticsApiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.energisticsApiPINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public string getInterpretedFeatureUuid() {
    string ret = f2i.energisticsStandardsApi.energisticsApiPINVOKE.resqml2_0_AbstractFeatureInterpretation_getInterpretedFeatureUuid(swigCPtr);
    if (f2i.energisticsStandardsApi.energisticsApiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.energisticsApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public WellboreMarkerFrameRepresentationVector getWellboreMarkerFrameRepresentationSet() {
    WellboreMarkerFrameRepresentationVector ret = new WellboreMarkerFrameRepresentationVector(f2i.energisticsStandardsApi.energisticsApiPINVOKE.resqml2_0_AbstractFeatureInterpretation_getWellboreMarkerFrameRepresentationSet(swigCPtr), true);
    if (f2i.energisticsStandardsApi.energisticsApiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.energisticsApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
