//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace f2i.energisticsStandardsApi.resqml2_0 {

public class StructuralOrganizationInterpretation : f2i.energisticsStandardsApi.resqml2_0.AbstractOrganizationInterpretation {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal StructuralOrganizationInterpretation(global::System.IntPtr cPtr, bool cMemoryOwn) : base(f2i.energisticsStandardsApi.fesapiPINVOKE.resqml2_0_StructuralOrganizationInterpretation_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StructuralOrganizationInterpretation obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~StructuralOrganizationInterpretation() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          f2i.energisticsStandardsApi.fesapiPINVOKE.delete_resqml2_0_StructuralOrganizationInterpretation(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public void pushBackFaultInterpretation(f2i.energisticsStandardsApi.resqml2_0.FaultInterpretation faultInterpretation) {
    f2i.energisticsStandardsApi.fesapiPINVOKE.resqml2_0_StructuralOrganizationInterpretation_pushBackFaultInterpretation(swigCPtr, f2i.energisticsStandardsApi.resqml2_0.FaultInterpretation.getCPtr(faultInterpretation));
    if (f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pushBackHorizonInterpretation(f2i.energisticsStandardsApi.resqml2_0.HorizonInterpretation horizonInterpretation, int stratigraphicRank) {
    f2i.energisticsStandardsApi.fesapiPINVOKE.resqml2_0_StructuralOrganizationInterpretation_pushBackHorizonInterpretation(swigCPtr, f2i.energisticsStandardsApi.resqml2_0.HorizonInterpretation.getCPtr(horizonInterpretation), stratigraphicRank);
    if (f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pushBackTopFrontierInterpretation(f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation topFrontierInterpretation) {
    f2i.energisticsStandardsApi.fesapiPINVOKE.resqml2_0_StructuralOrganizationInterpretation_pushBackTopFrontierInterpretation(swigCPtr, f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(topFrontierInterpretation));
    if (f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pushBackBottomFrontierInterpretation(f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation bottomFrontierInterpretation) {
    f2i.energisticsStandardsApi.fesapiPINVOKE.resqml2_0_StructuralOrganizationInterpretation_pushBackBottomFrontierInterpretation(swigCPtr, f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(bottomFrontierInterpretation));
    if (f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pushBackSideFrontierInterpretation(f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation sideFrontierInterpretation) {
    f2i.energisticsStandardsApi.fesapiPINVOKE.resqml2_0_StructuralOrganizationInterpretation_pushBackSideFrontierInterpretation(swigCPtr, f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(sideFrontierInterpretation));
    if (f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint getFaultInterpretationCount() {
    uint ret = f2i.energisticsStandardsApi.fesapiPINVOKE.resqml2_0_StructuralOrganizationInterpretation_getFaultInterpretationCount(swigCPtr);
    if (f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public f2i.energisticsStandardsApi.resqml2_0.FaultInterpretation getFaultInterpretation(uint index) {
    global::System.IntPtr cPtr = f2i.energisticsStandardsApi.fesapiPINVOKE.resqml2_0_StructuralOrganizationInterpretation_getFaultInterpretation(swigCPtr, index);
    f2i.energisticsStandardsApi.resqml2_0.FaultInterpretation ret = (cPtr == global::System.IntPtr.Zero) ? null : new f2i.energisticsStandardsApi.resqml2_0.FaultInterpretation(cPtr, false);
    if (f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Pending) throw f2i.energisticsStandardsApi.fesapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
