/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class AbstractLocal3dCrs extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractResqmlDataObject {
  private long swigCPtr;

  public AbstractLocal3dCrs(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AbstractLocal3dCrs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_AbstractLocal3dCrs(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public double getOriginOrdinal1() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_getOriginOrdinal1(swigCPtr, this);
  }

  public double getOriginOrdinal2() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_getOriginOrdinal2(swigCPtr, this);
  }

  public double getOriginDepthOrElevation() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_getOriginDepthOrElevation(swigCPtr, this);
  }

  public double getArealRotation() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_getArealRotation(swigCPtr, this);
  }

  public boolean isDepthOriented() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_isDepthOriented(swigCPtr, this);
  }

  public java.math.BigInteger getProjectedCrsEpsgCode() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_getProjectedCrsEpsgCode(swigCPtr, this);
  }

  public java.math.BigInteger getVerticalCrsEpsgCode() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_getVerticalCrsEpsgCode(swigCPtr, this);
  }

  public eml__LengthUom getProjectedCrsUnit() {
    return eml__LengthUom.swigToEnum(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_getProjectedCrsUnit(swigCPtr, this));
  }

  public String getProjectedCrsUnitAsString() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_getProjectedCrsUnitAsString(swigCPtr, this);
  }

  public eml__LengthUom getVerticalCrsUnit() {
    return eml__LengthUom.swigToEnum(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_getVerticalCrsUnit(swigCPtr, this));
  }

  public String getVerticalCrsUnitAsString() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_getVerticalCrsUnitAsString(swigCPtr, this);
  }

  public eml__AxisOrder2d getAxisOrder() {
    return eml__AxisOrder2d.swigToEnum(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractLocal3dCrs_getAxisOrder(swigCPtr, this));
  }

}
