/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class AbstractFeature extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractResqmlDataObject {
  private long swigCPtr;

  public AbstractFeature(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractFeature_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AbstractFeature obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_AbstractFeature(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long getInterpretationCount() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractFeature_getInterpretationCount(swigCPtr, this);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation getInterpretation(long index) {
		long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractFeature_getInterpretation(swigCPtr, this, index);
		com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation ret = (com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation) energisticsApiJNI.resqml2_0_instantiateConcreteObject(cPtr, false);
		return ret;
	}

}
