/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class AbstractRepresentation extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractResqmlDataObject {
  private long swigCPtr;

  public AbstractRepresentation(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AbstractRepresentation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_AbstractRepresentation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation getInterpretation() {
		long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getInterpretation(swigCPtr, this);
		com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation ret = (com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation) energisticsApiJNI.resqml2_0_instantiateConcreteObject(cPtr, false);
		return ret;
	}

  public String getInterpretationUuid() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getInterpretationUuid(swigCPtr, this);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs getLocalCrs() {
		long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getLocalCrs(swigCPtr, this);
		com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs ret = (com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs) energisticsApiJNI.resqml2_0_instantiateConcreteLocal3dCrs(cPtr, false);
		return ret;
	}

  public String getLocalCrsUuid() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getLocalCrsUuid(swigCPtr, this);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy getHdfProxy() {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getHdfProxy(swigCPtr, this);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy(cPtr, false);
  }

  public String getHdfProxyUuid() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getHdfProxyUuid(swigCPtr, this);
  }

  public long getValuesPropertyCount() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getValuesPropertyCount(swigCPtr, this);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty getValuesProperty(long index) {
		long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getValuesProperty(swigCPtr, this, index);
		com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty ret = (com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty) energisticsApiJNI.resqml2_0_instantiateConcreteObject(cPtr, false);
		return ret;
	}

  public long getSubRepresentationCount() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getSubRepresentationCount(swigCPtr, this);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.SubRepresentation getSubRepresentation(long index) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getSubRepresentation(swigCPtr, this, index);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.SubRepresentation(cPtr, false);
  }

  public long getFaultSubRepresentationCount() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getFaultSubRepresentationCount(swigCPtr, this);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.SubRepresentation getFaultSubRepresentation(long index) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getFaultSubRepresentation(swigCPtr, this, index);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.SubRepresentation(cPtr, false);
  }

  public long getXyzPointCountOfPatch(long patchIndex) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getXyzPointCountOfPatch(swigCPtr, this, patchIndex);
  }

  public long getXyzPointCountOfAllPatches() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getXyzPointCountOfAllPatches(swigCPtr, this);
  }

  public void getXyzPointsOfPatch(long patchIndex, SWIGTYPE_p_double xyzPoints) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getXyzPointsOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_double.getCPtr(xyzPoints));
  }

  public void getXyzPointsOfPatchInGlobalCrs(long patchIndex, SWIGTYPE_p_double xyzPoints) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getXyzPointsOfPatchInGlobalCrs(swigCPtr, this, patchIndex, SWIGTYPE_p_double.getCPtr(xyzPoints));
  }

  public void getXyzPointsOfAllPatches(SWIGTYPE_p_double xyzPoints) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getXyzPointsOfAllPatches(swigCPtr, this, SWIGTYPE_p_double.getCPtr(xyzPoints));
  }

  public void getXyzPointsOfAllPatchesInGlobalCrs(SWIGTYPE_p_double xyzPoints) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getXyzPointsOfAllPatchesInGlobalCrs(swigCPtr, this, SWIGTYPE_p_double.getCPtr(xyzPoints));
  }

  public long getPatchCount() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getPatchCount(swigCPtr, this);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation getSeismicSupportOfPatch(long patchIndex) {
		long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getSeismicSupportOfPatch(swigCPtr, this, patchIndex);
		com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation ret = (com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation) energisticsApiJNI.resqml2_0_instantiateConcreteObject(cPtr, false);
		return ret;
	}

  public void getSeismicLineAbscissaOfPointsOfPatch(long patchIndex, SWIGTYPE_p_double values) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_getSeismicLineAbscissaOfPointsOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_double.getCPtr(values));
  }

  public void addSeismic2dCoordinatesToPatch(long patchIndex, SWIGTYPE_p_double lineAbscissa, long pointCount, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation seismicSupport, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_addSeismic2dCoordinatesToPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_double.getCPtr(lineAbscissa), pointCount, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(seismicSupport), seismicSupport, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void addSeismic3dCoordinatesToPatch(long patchIndex, SWIGTYPE_p_double inlines, SWIGTYPE_p_double crosslines, long pointCount, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation seismicSupport, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_addSeismic3dCoordinatesToPatch__SWIG_0(swigCPtr, this, patchIndex, SWIGTYPE_p_double.getCPtr(inlines), SWIGTYPE_p_double.getCPtr(crosslines), pointCount, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(seismicSupport), seismicSupport, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void addSeismic3dCoordinatesToPatch(long patchIndex, double startInline, double incrInline, long countInline, double startCrossline, double incrCrossline, long countCrossline, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation seismicSupport) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_addSeismic3dCoordinatesToPatch__SWIG_1(swigCPtr, this, patchIndex, startInline, incrInline, countInline, startCrossline, incrCrossline, countCrossline, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(seismicSupport), seismicSupport);
  }

  public void pushBackIntoRepresentationSet(com.f2i.energisticsStandardsApi.resqml2_0.RepresentationSetRepresentation repSet) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractRepresentation_pushBackIntoRepresentationSet(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.RepresentationSetRepresentation.getCPtr(repSet), repSet);
  }

}
