/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class AbstractValuesProperty extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractProperty {
  private long swigCPtr;

  public AbstractValuesProperty(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractValuesProperty_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AbstractValuesProperty obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_AbstractValuesProperty(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum getValuesHdfDatatype() {
    return com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum.swigToEnum(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractValuesProperty_getValuesHdfDatatype(swigCPtr, this));
  }

  public int getNullValueOfPatch(long patchIndex) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractValuesProperty_getNullValueOfPatch(swigCPtr, this, patchIndex);
  }

  public int getLongValuesOfPatch(long patchIndex, SWIGTYPE_p_long values) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractValuesProperty_getLongValuesOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_long.getCPtr(values));
  }

  public long getULongValuesOfPatch(long patchIndex, SWIGTYPE_p_unsigned_long values) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractValuesProperty_getULongValuesOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_unsigned_long.getCPtr(values));
  }

  public int getIntValuesOfPatch(long patchIndex, SWIGTYPE_p_int values) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractValuesProperty_getIntValuesOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_int.getCPtr(values));
  }

  public long getUIntValuesOfPatch(long patchIndex, SWIGTYPE_p_unsigned_int values) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractValuesProperty_getUIntValuesOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_unsigned_int.getCPtr(values));
  }

  public short getShortValuesOfPatch(long patchIndex, SWIGTYPE_p_short values) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractValuesProperty_getShortValuesOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_short.getCPtr(values));
  }

  public int getUShortValuesOfPatch(long patchIndex, SWIGTYPE_p_unsigned_short values) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractValuesProperty_getUShortValuesOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_unsigned_short.getCPtr(values));
  }

  public char getCharValuesOfPatch(long patchIndex, String values) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractValuesProperty_getCharValuesOfPatch(swigCPtr, this, patchIndex, values);
  }

  public short getUCharValuesOfPatch(long patchIndex, SWIGTYPE_p_unsigned_char values) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractValuesProperty_getUCharValuesOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_unsigned_char.getCPtr(values));
  }

  public final static class hdfDatatypeEnum {
    public final static com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum UNKNOWN = new com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum("UNKNOWN", com.f2i.energisticsStandardsApi.energisticsApiJNI.AbstractValuesProperty_UNKNOWN_get());
    public final static com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum DOUBLE = new com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum("DOUBLE", com.f2i.energisticsStandardsApi.energisticsApiJNI.AbstractValuesProperty_DOUBLE_get());
    public final static com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum FLOAT = new com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum("FLOAT", com.f2i.energisticsStandardsApi.energisticsApiJNI.AbstractValuesProperty_FLOAT_get());
    public final static com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum LONG = new com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum("LONG", com.f2i.energisticsStandardsApi.energisticsApiJNI.AbstractValuesProperty_LONG_get());
    public final static com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum ULONG = new com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum("ULONG", com.f2i.energisticsStandardsApi.energisticsApiJNI.AbstractValuesProperty_ULONG_get());
    public final static com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum INT = new com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum("INT", com.f2i.energisticsStandardsApi.energisticsApiJNI.AbstractValuesProperty_INT_get());
    public final static com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum UINT = new com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum("UINT", com.f2i.energisticsStandardsApi.energisticsApiJNI.AbstractValuesProperty_UINT_get());
    public final static com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum SHORT = new com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum("SHORT", com.f2i.energisticsStandardsApi.energisticsApiJNI.AbstractValuesProperty_SHORT_get());
    public final static com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum USHORT = new com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum("USHORT", com.f2i.energisticsStandardsApi.energisticsApiJNI.AbstractValuesProperty_USHORT_get());
    public final static com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum CHAR = new com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum("CHAR", com.f2i.energisticsStandardsApi.energisticsApiJNI.AbstractValuesProperty_CHAR_get());
    public final static com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum UCHAR = new com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty.hdfDatatypeEnum("UCHAR", com.f2i.energisticsStandardsApi.energisticsApiJNI.AbstractValuesProperty_UCHAR_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static hdfDatatypeEnum swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + hdfDatatypeEnum.class + " with value " + swigValue);
    }

    private hdfDatatypeEnum(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private hdfDatatypeEnum(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private hdfDatatypeEnum(String swigName, hdfDatatypeEnum swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static hdfDatatypeEnum[] swigValues = { UNKNOWN, DOUBLE, FLOAT, LONG, ULONG, INT, UINT, SHORT, USHORT, CHAR, UCHAR };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
