/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class AbstractGridRepresentation extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation {
  private long swigCPtr;

  public AbstractGridRepresentation(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractGridRepresentation_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AbstractGridRepresentation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_AbstractGridRepresentation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long getGridConnectionSetRepresentationCount() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractGridRepresentation_getGridConnectionSetRepresentationCount(swigCPtr, this);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.GridConnectionSetRepresentation getGridConnectionSetRepresentation(long index) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_AbstractGridRepresentation_getGridConnectionSetRepresentation(swigCPtr, this, index);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.GridConnectionSetRepresentation(cPtr, false);
  }

}
