/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class CommentProperty extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty {
  private long swigCPtr;

  public CommentProperty(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_CommentProperty_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(CommentProperty obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_CommentProperty(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void pushBackStringHdf5ArrayOfValues(StringVector values, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_CommentProperty_pushBackStringHdf5ArrayOfValues(swigCPtr, this, StringVector.getCPtr(values), values, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public StringVector getStringValuesOfPatch(long patchIndex) {
    return new StringVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_CommentProperty_getStringValuesOfPatch(swigCPtr, this, patchIndex), true);
  }

}
