/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class ContinuousProperty extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty {
  private long swigCPtr;

  public ContinuousProperty(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ContinuousProperty obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_ContinuousProperty(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public resqml2__ResqmlUom getUom() {
    return resqml2__ResqmlUom.swigToEnum(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_getUom(swigCPtr, this));
  }

  public String getUomAsString() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_getUomAsString(swigCPtr, this);
  }

  public void pushBackDoubleHdf5Array1dOfValues(SWIGTYPE_p_double values, long valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue, double maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5Array1dOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue, maximumValue);
  }

  public void pushBackDoubleHdf5Array1dOfValues(SWIGTYPE_p_double values, long valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5Array1dOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue);
  }

  public void pushBackDoubleHdf5Array1dOfValues(SWIGTYPE_p_double values, long valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5Array1dOfValues__SWIG_2(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void pushBackDoubleHdf5Array2dOfValues(SWIGTYPE_p_double values, long valueCountInFastestDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue, double maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5Array2dOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), valueCountInFastestDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue, maximumValue);
  }

  public void pushBackDoubleHdf5Array2dOfValues(SWIGTYPE_p_double values, long valueCountInFastestDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5Array2dOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), valueCountInFastestDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue);
  }

  public void pushBackDoubleHdf5Array2dOfValues(SWIGTYPE_p_double values, long valueCountInFastestDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5Array2dOfValues__SWIG_2(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), valueCountInFastestDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void pushBackDoubleHdf5Array3dOfValues(SWIGTYPE_p_double values, long valueCountInFastestDim, long valueCountInMiddleDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue, double maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5Array3dOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), valueCountInFastestDim, valueCountInMiddleDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue, maximumValue);
  }

  public void pushBackDoubleHdf5Array3dOfValues(SWIGTYPE_p_double values, long valueCountInFastestDim, long valueCountInMiddleDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5Array3dOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), valueCountInFastestDim, valueCountInMiddleDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue);
  }

  public void pushBackDoubleHdf5Array3dOfValues(SWIGTYPE_p_double values, long valueCountInFastestDim, long valueCountInMiddleDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5Array3dOfValues__SWIG_2(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), valueCountInFastestDim, valueCountInMiddleDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void pushBackDoubleHdf5ArrayOfValues(SWIGTYPE_p_double values, SWIGTYPE_p_unsigned_long_long numValues, long numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, SWIGTYPE_p_double minimumValue, SWIGTYPE_p_double maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5ArrayOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), SWIGTYPE_p_unsigned_long_long.getCPtr(numValues), numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, SWIGTYPE_p_double.getCPtr(minimumValue), SWIGTYPE_p_double.getCPtr(maximumValue));
  }

  public void pushBackDoubleHdf5ArrayOfValues(SWIGTYPE_p_double values, SWIGTYPE_p_unsigned_long_long numValues, long numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, SWIGTYPE_p_double minimumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5ArrayOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), SWIGTYPE_p_unsigned_long_long.getCPtr(numValues), numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, SWIGTYPE_p_double.getCPtr(minimumValue));
  }

  public void pushBackDoubleHdf5ArrayOfValues(SWIGTYPE_p_double values, SWIGTYPE_p_unsigned_long_long numValues, long numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackDoubleHdf5ArrayOfValues__SWIG_2(swigCPtr, this, SWIGTYPE_p_double.getCPtr(values), SWIGTYPE_p_unsigned_long_long.getCPtr(numValues), numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void pushBackFloatHdf5Array1dOfValues(SWIGTYPE_p_float values, long valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue, double maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5Array1dOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue, maximumValue);
  }

  public void pushBackFloatHdf5Array1dOfValues(SWIGTYPE_p_float values, long valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5Array1dOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue);
  }

  public void pushBackFloatHdf5Array1dOfValues(SWIGTYPE_p_float values, long valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5Array1dOfValues__SWIG_2(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void pushBackFloatHdf5Array2dOfValues(SWIGTYPE_p_float values, long valueCountInFastestDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue, double maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5Array2dOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), valueCountInFastestDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue, maximumValue);
  }

  public void pushBackFloatHdf5Array2dOfValues(SWIGTYPE_p_float values, long valueCountInFastestDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5Array2dOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), valueCountInFastestDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue);
  }

  public void pushBackFloatHdf5Array2dOfValues(SWIGTYPE_p_float values, long valueCountInFastestDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5Array2dOfValues__SWIG_2(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), valueCountInFastestDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void pushBackFloatHdf5Array3dOfValues(SWIGTYPE_p_float values, long valueCountInFastestDim, long valueCountInMiddleDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue, double maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5Array3dOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), valueCountInFastestDim, valueCountInMiddleDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue, maximumValue);
  }

  public void pushBackFloatHdf5Array3dOfValues(SWIGTYPE_p_float values, long valueCountInFastestDim, long valueCountInMiddleDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, double minimumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5Array3dOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), valueCountInFastestDim, valueCountInMiddleDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, minimumValue);
  }

  public void pushBackFloatHdf5Array3dOfValues(SWIGTYPE_p_float values, long valueCountInFastestDim, long valueCountInMiddleDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5Array3dOfValues__SWIG_2(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), valueCountInFastestDim, valueCountInMiddleDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void pushBackFloatHdf5ArrayOfValues(SWIGTYPE_p_float values, SWIGTYPE_p_unsigned_long_long numValues, long numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, SWIGTYPE_p_double minimumValue, SWIGTYPE_p_double maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5ArrayOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), SWIGTYPE_p_unsigned_long_long.getCPtr(numValues), numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, SWIGTYPE_p_double.getCPtr(minimumValue), SWIGTYPE_p_double.getCPtr(maximumValue));
  }

  public void pushBackFloatHdf5ArrayOfValues(SWIGTYPE_p_float values, SWIGTYPE_p_unsigned_long_long numValues, long numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, SWIGTYPE_p_double minimumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5ArrayOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), SWIGTYPE_p_unsigned_long_long.getCPtr(numValues), numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, SWIGTYPE_p_double.getCPtr(minimumValue));
  }

  public void pushBackFloatHdf5ArrayOfValues(SWIGTYPE_p_float values, SWIGTYPE_p_unsigned_long_long numValues, long numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_pushBackFloatHdf5ArrayOfValues__SWIG_2(swigCPtr, this, SWIGTYPE_p_float.getCPtr(values), SWIGTYPE_p_unsigned_long_long.getCPtr(numValues), numArrayDimensions, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void getDoubleValuesOfPatch(long patchIndex, SWIGTYPE_p_double values) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_getDoubleValuesOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_double.getCPtr(values));
  }

  public void getFloatValuesOfPatch(long patchIndex, SWIGTYPE_p_float values) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_ContinuousProperty_getFloatValuesOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_float.getCPtr(values));
  }

}
