/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class DiscreteProperty extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractValuesProperty {
  private long swigCPtr;

  public DiscreteProperty(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_DiscreteProperty_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(DiscreteProperty obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_DiscreteProperty(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void pushBackLongHdf5Array1dOfValues(SWIGTYPE_p_long values, long valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, int nullValue, int minimumValue, int maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_DiscreteProperty_pushBackLongHdf5Array1dOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_long.getCPtr(values), valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, nullValue, minimumValue, maximumValue);
  }

  public void pushBackLongHdf5Array1dOfValues(SWIGTYPE_p_long values, long valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, int nullValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_DiscreteProperty_pushBackLongHdf5Array1dOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_long.getCPtr(values), valueCount, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, nullValue);
  }

  public void pushBackLongHdf5Array2dOfValues(SWIGTYPE_p_long values, long valueCountInFastestDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, int nullValue, int minimumValue, int maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_DiscreteProperty_pushBackLongHdf5Array2dOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_long.getCPtr(values), valueCountInFastestDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, nullValue, minimumValue, maximumValue);
  }

  public void pushBackLongHdf5Array2dOfValues(SWIGTYPE_p_long values, long valueCountInFastestDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, int nullValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_DiscreteProperty_pushBackLongHdf5Array2dOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_long.getCPtr(values), valueCountInFastestDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, nullValue);
  }

  public void pushBackLongHdf5Array3dOfValues(SWIGTYPE_p_long values, long valueCountInFastestDim, long valueCountInMiddleDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, int nullValue, int minimumValue, int maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_DiscreteProperty_pushBackLongHdf5Array3dOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_long.getCPtr(values), valueCountInFastestDim, valueCountInMiddleDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, nullValue, minimumValue, maximumValue);
  }

  public void pushBackLongHdf5Array3dOfValues(SWIGTYPE_p_long values, long valueCountInFastestDim, long valueCountInMiddleDim, long valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, int nullValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_DiscreteProperty_pushBackLongHdf5Array3dOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_long.getCPtr(values), valueCountInFastestDim, valueCountInMiddleDim, valueCountInSlowestDim, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, nullValue);
  }

  public void pushBackLongHdf5ArrayOfValues(SWIGTYPE_p_long values, SWIGTYPE_p_unsigned_long_long numValues, long numDimensionsInArray, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, int nullValue, int minimumValue, int maximumValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_DiscreteProperty_pushBackLongHdf5ArrayOfValues__SWIG_0(swigCPtr, this, SWIGTYPE_p_long.getCPtr(values), SWIGTYPE_p_unsigned_long_long.getCPtr(numValues), numDimensionsInArray, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, nullValue, minimumValue, maximumValue);
  }

  public void pushBackLongHdf5ArrayOfValues(SWIGTYPE_p_long values, SWIGTYPE_p_unsigned_long_long numValues, long numDimensionsInArray, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy, int nullValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_DiscreteProperty_pushBackLongHdf5ArrayOfValues__SWIG_1(swigCPtr, this, SWIGTYPE_p_long.getCPtr(values), SWIGTYPE_p_unsigned_long_long.getCPtr(numValues), numDimensionsInArray, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy, nullValue);
  }

}
