/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class GridConnectionSetRepresentation extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation {
  private long swigCPtr;

  public GridConnectionSetRepresentation(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(GridConnectionSetRepresentation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_GridConnectionSetRepresentation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long getCellIndexPairCount() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_getCellIndexPairCount(swigCPtr, this);
  }

  public long getCellIndexPairCountFromFaultIndex(long faultIndex) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_getCellIndexPairCountFromFaultIndex(swigCPtr, this, faultIndex);
  }

  public void getCellIndexPair(SWIGTYPE_p_unsigned_int cellIndexPair) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_getCellIndexPair(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(cellIndexPair));
  }

  public void getCellIndexPairFromFaultIndex(SWIGTYPE_p_unsigned_int cellIndexPair, long faultIndex) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_getCellIndexPairFromFaultIndex(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(cellIndexPair), faultIndex);
  }

  public void setCellIndexPairs(long cellIndexPairCount, SWIGTYPE_p_unsigned_int cellIndexPair, long nullValue, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_setCellIndexPairs(swigCPtr, this, cellIndexPairCount, SWIGTYPE_p_unsigned_int.getCPtr(cellIndexPair), nullValue, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void setLocalFacePerCellIndexPairs(long cellIndexPairCount, SWIGTYPE_p_unsigned_int LocalFacePerCellIndexPair, long nullValue, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_setLocalFacePerCellIndexPairs(swigCPtr, this, cellIndexPairCount, SWIGTYPE_p_unsigned_int.getCPtr(LocalFacePerCellIndexPair), nullValue, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void setConnectionFaultNames(SWIGTYPE_p_unsigned_int faultIndices, long faultIndiceCount, long nullValue, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_setConnectionFaultNames(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(faultIndices), faultIndiceCount, nullValue, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public String getFaultInterpretationUuidFromFaultIndex(long faultIndex) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_getFaultInterpretationUuidFromFaultIndex(swigCPtr, this, faultIndex);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.FaultInterpretation getFaultInterpretationFromFaultIndex(long faultIndex) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_getFaultInterpretationFromFaultIndex(swigCPtr, this, faultIndex);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.FaultInterpretation(cPtr, false);
  }

  public long getFaultInterpretationCount() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_getFaultInterpretationCount(swigCPtr, this);
  }

  public long getSupportingGridRepresentationCount() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_getSupportingGridRepresentationCount(swigCPtr, this);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.AbstractGridRepresentation getSupportingGridRepresentation() {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_getSupportingGridRepresentation(swigCPtr, this);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.AbstractGridRepresentation(cPtr, false);
  }

  public String getSupportingGridRepresentationUuid() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_GridConnectionSetRepresentation_getSupportingGridRepresentationUuid(swigCPtr, this);
  }

}
