/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class HdfProxy extends com.f2i.energisticsStandardsApi.resqml2_0.EpcExternalPartReference {
  private long swigCPtr;

  public HdfProxy(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_HdfProxy_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(HdfProxy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_HdfProxy(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean isOpened() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_HdfProxy_isOpened(swigCPtr, this);
  }

  public void close() {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_HdfProxy_close(swigCPtr, this);
  }

  public void setCompressionLevel(long newCompressionLevel) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_HdfProxy_setCompressionLevel(swigCPtr, this, newCompressionLevel);
  }

}
