/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class PolylineSetRepresentation extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation {
  private long swigCPtr;

  public PolylineSetRepresentation(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(PolylineSetRepresentation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_PolylineSetRepresentation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long getPolylineCountOfPatch(long patchIndex) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_getPolylineCountOfPatch(swigCPtr, this, patchIndex);
  }

  public long getPolylineCountOfAllPatches() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_getPolylineCountOfAllPatches(swigCPtr, this);
  }

  public void getNodeCountPerPolylineInPatch(long patchIndex, SWIGTYPE_p_unsigned_int nodeCountPerPolyline) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_getNodeCountPerPolylineInPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_unsigned_int.getCPtr(nodeCountPerPolyline));
  }

  public void getNodeCountPerPolylineOfAllPatches(SWIGTYPE_p_unsigned_int nodeCountPerPolyline) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_getNodeCountPerPolylineOfAllPatches(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(nodeCountPerPolyline));
  }

  public void pushBackGeometryPatch(SWIGTYPE_p_unsigned_int NodeCountPerPolyline, SWIGTYPE_p_double nodes, long polylineCount, boolean allPolylinesClosedFlag, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_pushBackGeometryPatch__SWIG_0(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(NodeCountPerPolyline), SWIGTYPE_p_double.getCPtr(nodes), polylineCount, allPolylinesClosedFlag, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void pushBackGeometryPatch(SWIGTYPE_p_unsigned_int NodeCountPerPolyline, SWIGTYPE_p_double nodes, long polylineCount, SWIGTYPE_p_bool polylineClosedFlags, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_pushBackGeometryPatch__SWIG_1(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(NodeCountPerPolyline), SWIGTYPE_p_double.getCPtr(nodes), polylineCount, SWIGTYPE_p_bool.getCPtr(polylineClosedFlags), com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public boolean areAllPolylinesClosedOfPatch(long patchIndex) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_areAllPolylinesClosedOfPatch(swigCPtr, this, patchIndex);
  }

  public boolean areAllPolylinesClosedOfAllPatches() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_areAllPolylinesClosedOfAllPatches(swigCPtr, this);
  }

  public boolean areAllPolylinesNonClosedOfPatch(long patchIndex) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_areAllPolylinesNonClosedOfPatch(swigCPtr, this, patchIndex);
  }

  public boolean areAllPolylinesNonClosedOfAllPatches() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_areAllPolylinesNonClosedOfAllPatches(swigCPtr, this);
  }

  public void getClosedFlagPerPolylineOfPatch(long patchIndex, SWIGTYPE_p_bool closedFlagPerPolyline) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_getClosedFlagPerPolylineOfPatch(swigCPtr, this, patchIndex, SWIGTYPE_p_bool.getCPtr(closedFlagPerPolyline));
  }

  public void getClosedFlagPerPolylineOfAllPatches(SWIGTYPE_p_bool closedFlagPerPolyline) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PolylineSetRepresentation_getClosedFlagPerPolylineOfAllPatches(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(closedFlagPerPolyline));
  }

}
