/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class PropertyKindMapper {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public PropertyKindMapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PropertyKindMapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_PropertyKindMapper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PropertyKindMapper(com.f2i.energisticsStandardsApi.common.EpcDocument epcDoc) {
    this(com.f2i.energisticsStandardsApi.energisticsApiJNI.new_resqml2_0_PropertyKindMapper(com.f2i.energisticsStandardsApi.common.EpcDocument.getCPtr(epcDoc), epcDoc), true);
  }

  public String loadMappingFilesFromDirectory(String directory) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PropertyKindMapper_loadMappingFilesFromDirectory(swigCPtr, this, directory);
  }

  public String getUomOfResqmlStandardPropertyKindName(resqml2__ResqmlPropertyKind resqmlStandardPropertyKindName) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PropertyKindMapper_getUomOfResqmlStandardPropertyKindName(swigCPtr, this, resqmlStandardPropertyKindName.swigValue());
  }

  public String getApplicationPropertyKindNameFromResqmlStandardPropertyKindName(resqml2__ResqmlPropertyKind resqmlStandardPropertyKindName, String application) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PropertyKindMapper_getApplicationPropertyKindNameFromResqmlStandardPropertyKindName(swigCPtr, this, resqmlStandardPropertyKindName.swigValue(), application);
  }

  public resqml2__ResqmlPropertyKind getResqmlStandardPropertyKindNameFromApplicationPropertyKindName(String applicationPropertyKindName, String application) {
    return resqml2__ResqmlPropertyKind.swigToEnum(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PropertyKindMapper_getResqmlStandardPropertyKindNameFromApplicationPropertyKindName(swigCPtr, this, applicationPropertyKindName, application));
  }

  public String getApplicationPropertyKindNameFromResqmlLocalPropertyKindUuid(String resqmlLocalPropertyKindUuid, String application) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PropertyKindMapper_getApplicationPropertyKindNameFromResqmlLocalPropertyKindUuid(swigCPtr, this, resqmlLocalPropertyKindUuid, application);
  }

  public String getResqmlLocalPropertyKindUuidFromApplicationPropertyKindName(String applicationPropertyKindName, String application) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PropertyKindMapper_getResqmlLocalPropertyKindUuidFromApplicationPropertyKindName(swigCPtr, this, applicationPropertyKindName, application);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind addResqmlLocalPropertyKindToEpcDocumentFromApplicationPropertyKindName(String applicationPropertyKindName, String application) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_PropertyKindMapper_addResqmlLocalPropertyKindToEpcDocumentFromApplicationPropertyKindName(swigCPtr, this, applicationPropertyKindName, application);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind(cPtr, false);
  }

}
