/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class StratigraphicOccurrenceInterpretation extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractOrganizationInterpretation {
  private long swigCPtr;

  public StratigraphicOccurrenceInterpretation(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_StratigraphicOccurrenceInterpretation_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(StratigraphicOccurrenceInterpretation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_StratigraphicOccurrenceInterpretation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setStratigraphicColumnRankInterpretation(com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumnRankInterpretation stratiColumnRankInterp) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_StratigraphicOccurrenceInterpretation_setStratigraphicColumnRankInterpretation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumnRankInterpretation.getCPtr(stratiColumnRankInterp), stratiColumnRankInterp);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumnRankInterpretation getStratigraphicColumnRankInterpretation() {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_StratigraphicOccurrenceInterpretation_getStratigraphicColumnRankInterpretation(swigCPtr, this);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumnRankInterpretation(cPtr, false);
  }

  public String getStratigraphicColumnRankInterpretationUuid() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_StratigraphicOccurrenceInterpretation_getStratigraphicColumnRankInterpretationUuid(swigCPtr, this);
  }

}
