/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class StringTableLookup extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractResqmlDataObject {
  private long swigCPtr;

  public StringTableLookup(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_StringTableLookup_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(StringTableLookup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_StringTableLookup(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long getItemCount() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_StringTableLookup_getItemCount(swigCPtr, this);
  }

  public int getKeyAtIndex(long index) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_StringTableLookup_getKeyAtIndex(swigCPtr, this, index);
  }

  public String getStringValueAtIndex(long index) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_StringTableLookup_getStringValueAtIndex(swigCPtr, this, index);
  }

  public String getStringValue(int longValue) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_StringTableLookup_getStringValue(swigCPtr, this, longValue);
  }

  public void addValue(String strValue, int longValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_StringTableLookup_addValue(swigCPtr, this, strValue, longValue);
  }

  public void setValue(String strValue, int longValue) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_StringTableLookup_setValue(swigCPtr, this, strValue, longValue);
  }

}
