/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.resqml2_0;

		import com.f2i.energisticsStandardsApi.*;
	
public class SubRepresentation extends com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation {
  private long swigCPtr;

  public SubRepresentation(long cPtr, boolean cMemoryOwn) {
    super(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_SubRepresentation_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(SubRepresentation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_resqml2_0_SubRepresentation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void pushBackSubRepresentationPatch(resqml2__IndexableElements elementKind, long elementCount, SWIGTYPE_p_unsigned_int elementIndices, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_SubRepresentation_pushBackSubRepresentationPatch__SWIG_0(swigCPtr, this, elementKind.swigValue(), elementCount, SWIGTYPE_p_unsigned_int.getCPtr(elementIndices), com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public void pushBackSubRepresentationPatch(resqml2__IndexableElements elementKind0, resqml2__IndexableElements elementKind1, long elementCount, SWIGTYPE_p_unsigned_int elementIndices0, SWIGTYPE_p_unsigned_int elementIndices1, com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy proxy) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_SubRepresentation_pushBackSubRepresentationPatch__SWIG_1(swigCPtr, this, elementKind0.swigValue(), elementKind1.swigValue(), elementCount, SWIGTYPE_p_unsigned_int.getCPtr(elementIndices0), SWIGTYPE_p_unsigned_int.getCPtr(elementIndices1), com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy.getCPtr(proxy), proxy);
  }

  public boolean isElementPairBased(long patchIndex) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_SubRepresentation_isElementPairBased(swigCPtr, this, patchIndex);
  }

  public resqml2__IndexableElements getElementKindOfPatch(long patchIndex, long elementIndicesIndex) {
    return resqml2__IndexableElements.swigToEnum(com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_SubRepresentation_getElementKindOfPatch(swigCPtr, this, patchIndex, elementIndicesIndex));
  }

  public long getElementCountOfPatch(long patchIndex) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_SubRepresentation_getElementCountOfPatch(swigCPtr, this, patchIndex);
  }

  public void getElementIndicesOfPatch(long patchIndex, long elementIndicesIndex, SWIGTYPE_p_unsigned_int elementIndices) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.resqml2_0_SubRepresentation_getElementIndicesOfPatch(swigCPtr, this, patchIndex, elementIndicesIndex, SWIGTYPE_p_unsigned_int.getCPtr(elementIndices));
  }

}
