//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace f2i.energisticsStandardsApi {

public enum resqml2__IndexableElements {
  resqml2__IndexableElements__cells = 0,
  resqml2__IndexableElements__column_x0020edges = 1,
  resqml2__IndexableElements__columns = 2,
  resqml2__IndexableElements__contacts = 3,
  resqml2__IndexableElements__coordinate_x0020lines = 4,
  resqml2__IndexableElements__edges = 5,
  resqml2__IndexableElements__edges_x0020per_x0020column = 6,
  resqml2__IndexableElements__enumerated_x0020elements = 7,
  resqml2__IndexableElements__faces = 8,
  resqml2__IndexableElements__faces_x0020per_x0020cell = 9,
  resqml2__IndexableElements__interval_x0020edges = 10,
  resqml2__IndexableElements__intervals = 11,
  resqml2__IndexableElements__I0 = 12,
  resqml2__IndexableElements__I0_x0020edges = 13,
  resqml2__IndexableElements__J0 = 14,
  resqml2__IndexableElements__J0_x0020edges = 15,
  resqml2__IndexableElements__layers = 16,
  resqml2__IndexableElements__nodes = 17,
  resqml2__IndexableElements__nodes_x0020per_x0020cell = 18,
  resqml2__IndexableElements__nodes_x0020per_x0020edge = 19,
  resqml2__IndexableElements__nodes_x0020per_x0020face = 20,
  resqml2__IndexableElements__patches = 21,
  resqml2__IndexableElements__pillars = 22,
  resqml2__IndexableElements__regions = 23,
  resqml2__IndexableElements__representation = 24,
  resqml2__IndexableElements__subnodes = 25,
  resqml2__IndexableElements__triangles = 26
}

}
