//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace f2i.energisticsStandardsApi {

public enum resqml2__PillarShape {
  resqml2__PillarShape__vertical = 0,
  resqml2__PillarShape__straight = 1,
  resqml2__PillarShape__curved = 2
}

}
