//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace f2i.energisticsStandardsApi {

public enum resqml2__LineRole {
  resqml2__LineRole__fault_x0020center_x0020line = 0,
  resqml2__LineRole__pick = 1,
  resqml2__LineRole__inner_x0020ring = 2,
  resqml2__LineRole__outer_x0020ring = 3,
  resqml2__LineRole__trajectory = 4,
  resqml2__LineRole__interpretation_x0020line = 5,
  resqml2__LineRole__contact = 6,
  resqml2__LineRole__depositional_x0020line = 7,
  resqml2__LineRole__erosion_x0020line = 8,
  resqml2__LineRole__contouring = 9,
  resqml2__LineRole__pillar = 10
}

}
