//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace f2i.energisticsStandardsApi {

public enum resqml2__ContactMode {
  resqml2__ContactMode__baselap = 0,
  resqml2__ContactMode__erosion = 1,
  resqml2__ContactMode__extended = 2,
  resqml2__ContactMode__proportional = 3
}

}
