//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace f2i.energisticsStandardsApi {

public class UCharArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UCharArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UCharArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UCharArray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          energisticsApiPINVOKE.delete_UCharArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public UCharArray(int nelements) : this(energisticsApiPINVOKE.new_UCharArray(nelements), true) {
  }

  public byte getitem(int index) {
    byte ret = energisticsApiPINVOKE.UCharArray_getitem(swigCPtr, index);
    return ret;
  }

  public void setitem(int index, byte value) {
    energisticsApiPINVOKE.UCharArray_setitem(swigCPtr, index, value);
  }

  public SWIGTYPE_p_unsigned_char cast() {
    global::System.IntPtr cPtr = energisticsApiPINVOKE.UCharArray_cast(swigCPtr);
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public static UCharArray frompointer(SWIGTYPE_p_unsigned_char t) {
    global::System.IntPtr cPtr = energisticsApiPINVOKE.UCharArray_frompointer(SWIGTYPE_p_unsigned_char.getCPtr(t));
    UCharArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new UCharArray(cPtr, false);
    return ret;
  }

}

}
