//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace f2i.energisticsStandardsApi {

public enum witsml1__MeasuredDepthUom {
  witsml1__MeasuredDepthUom__m = 0,
  witsml1__MeasuredDepthUom__ft = 1,
  witsml1__MeasuredDepthUom__ftUS = 2
}

}
