//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace f2i.energisticsStandardsApi {

public enum witsml1__PerLengthUom {
  witsml1__PerLengthUom__1_x002fm = 0,
  witsml1__PerLengthUom__1_x002fangstrom = 1,
  witsml1__PerLengthUom__1_x002fcm = 2,
  witsml1__PerLengthUom__1_x002fft = 3,
  witsml1__PerLengthUom__1_x002fin = 4,
  witsml1__PerLengthUom__1_x002fmi = 5,
  witsml1__PerLengthUom__1_x002fmm = 6,
  witsml1__PerLengthUom__1_x002fnm = 7,
  witsml1__PerLengthUom__1_x002fyd = 8
}

}
