//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace f2i.energisticsStandardsApi {

public enum witsml1__LengthUom {
  witsml1__LengthUom__m = 0,
  witsml1__LengthUom__angstrom = 1,
  witsml1__LengthUom__chBnA = 2,
  witsml1__LengthUom__chBnB = 3,
  witsml1__LengthUom__chCla = 4,
  witsml1__LengthUom__chSe = 5,
  witsml1__LengthUom__chUS = 6,
  witsml1__LengthUom__cm = 7,
  witsml1__LengthUom__dm = 8,
  witsml1__LengthUom__fathom = 9,
  witsml1__LengthUom__fm = 10,
  witsml1__LengthUom__ft = 11,
  witsml1__LengthUom__ftBnA = 12,
  witsml1__LengthUom__ftBnB = 13,
  witsml1__LengthUom__ftBr_x002865_x0029 = 14,
  witsml1__LengthUom__ftCla = 15,
  witsml1__LengthUom__ftGC = 16,
  witsml1__LengthUom__ftInd = 17,
  witsml1__LengthUom__ftInd_x002837_x0029 = 18,
  witsml1__LengthUom__ftInd_x002862_x0029 = 19,
  witsml1__LengthUom__ftInd_x002875_x0029 = 20,
  witsml1__LengthUom__ftMA = 21,
  witsml1__LengthUom__ftSe = 22,
  witsml1__LengthUom__ftUS = 23,
  witsml1__LengthUom__in = 24,
  witsml1__LengthUom__in_x002f10 = 25,
  witsml1__LengthUom__in_x002f16 = 26,
  witsml1__LengthUom__in_x002f32 = 27,
  witsml1__LengthUom__in_x002f64 = 28,
  witsml1__LengthUom__inUS = 29,
  witsml1__LengthUom__km = 30,
  witsml1__LengthUom__lkBnA = 31,
  witsml1__LengthUom__lkBnB = 32,
  witsml1__LengthUom__lkCla = 33,
  witsml1__LengthUom__lkSe = 34,
  witsml1__LengthUom__lkUS = 35,
  witsml1__LengthUom__mGer = 36,
  witsml1__LengthUom__mi = 37,
  witsml1__LengthUom__mil = 38,
  witsml1__LengthUom__miUS = 39,
  witsml1__LengthUom__mm = 40,
  witsml1__LengthUom__Mm = 41,
  witsml1__LengthUom__nautmi = 42,
  witsml1__LengthUom__nm = 43,
  witsml1__LengthUom__pm = 44,
  witsml1__LengthUom__um = 45,
  witsml1__LengthUom__yd = 46,
  witsml1__LengthUom__ydBnA = 47,
  witsml1__LengthUom__ydBnB = 48,
  witsml1__LengthUom__ydCla = 49,
  witsml1__LengthUom__ydIm = 50,
  witsml1__LengthUom__ydInd = 51,
  witsml1__LengthUom__ydInd_x002837_x0029 = 52,
  witsml1__LengthUom__ydInd_x002862_x0029 = 53,
  witsml1__LengthUom__ydInd_x002875_x0029 = 54,
  witsml1__LengthUom__ydSe = 55
}

}
