//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace f2i.energisticsStandardsApi {

public enum witsml1__PlaneAngleUom {
  witsml1__PlaneAngleUom__rad = 0,
  witsml1__PlaneAngleUom__c = 1,
  witsml1__PlaneAngleUom__ccgr = 2,
  witsml1__PlaneAngleUom__cgr = 3,
  witsml1__PlaneAngleUom__dega = 4,
  witsml1__PlaneAngleUom__gon = 5,
  witsml1__PlaneAngleUom__gr = 6,
  witsml1__PlaneAngleUom__Grad = 7,
  witsml1__PlaneAngleUom__krad = 8,
  witsml1__PlaneAngleUom__mila = 9,
  witsml1__PlaneAngleUom__mina = 10,
  witsml1__PlaneAngleUom__mrad = 11,
  witsml1__PlaneAngleUom__Mrad = 12,
  witsml1__PlaneAngleUom__mseca = 13,
  witsml1__PlaneAngleUom__seca = 14,
  witsml1__PlaneAngleUom__urad = 15
}

}
