/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public final class eml__TimeUom {
  public final static eml__TimeUom eml__TimeUom__1_x002f2_x0020ms = new eml__TimeUom("eml__TimeUom__1_x002f2_x0020ms", energisticsApiJNI.eml__TimeUom__1_x002f2_x0020ms_get());
  public final static eml__TimeUom eml__TimeUom__100_x0020ka_x005bt_x005d = new eml__TimeUom("eml__TimeUom__100_x0020ka_x005bt_x005d", energisticsApiJNI.eml__TimeUom__100_x0020ka_x005bt_x005d_get());
  public final static eml__TimeUom eml__TimeUom__a = new eml__TimeUom("eml__TimeUom__a", energisticsApiJNI.eml__TimeUom__a_get());
  public final static eml__TimeUom eml__TimeUom__a_x005bt_x005d = new eml__TimeUom("eml__TimeUom__a_x005bt_x005d", energisticsApiJNI.eml__TimeUom__a_x005bt_x005d_get());
  public final static eml__TimeUom eml__TimeUom__ca = new eml__TimeUom("eml__TimeUom__ca", energisticsApiJNI.eml__TimeUom__ca_get());
  public final static eml__TimeUom eml__TimeUom__cs = new eml__TimeUom("eml__TimeUom__cs", energisticsApiJNI.eml__TimeUom__cs_get());
  public final static eml__TimeUom eml__TimeUom__d = new eml__TimeUom("eml__TimeUom__d", energisticsApiJNI.eml__TimeUom__d_get());
  public final static eml__TimeUom eml__TimeUom__ds = new eml__TimeUom("eml__TimeUom__ds", energisticsApiJNI.eml__TimeUom__ds_get());
  public final static eml__TimeUom eml__TimeUom__Ea_x005bt_x005d = new eml__TimeUom("eml__TimeUom__Ea_x005bt_x005d", energisticsApiJNI.eml__TimeUom__Ea_x005bt_x005d_get());
  public final static eml__TimeUom eml__TimeUom__fa = new eml__TimeUom("eml__TimeUom__fa", energisticsApiJNI.eml__TimeUom__fa_get());
  public final static eml__TimeUom eml__TimeUom__Ga_x005bt_x005d = new eml__TimeUom("eml__TimeUom__Ga_x005bt_x005d", energisticsApiJNI.eml__TimeUom__Ga_x005bt_x005d_get());
  public final static eml__TimeUom eml__TimeUom__h = new eml__TimeUom("eml__TimeUom__h", energisticsApiJNI.eml__TimeUom__h_get());
  public final static eml__TimeUom eml__TimeUom__hs = new eml__TimeUom("eml__TimeUom__hs", energisticsApiJNI.eml__TimeUom__hs_get());
  public final static eml__TimeUom eml__TimeUom__ka_x005bt_x005d = new eml__TimeUom("eml__TimeUom__ka_x005bt_x005d", energisticsApiJNI.eml__TimeUom__ka_x005bt_x005d_get());
  public final static eml__TimeUom eml__TimeUom__Ma_x005bt_x005d = new eml__TimeUom("eml__TimeUom__Ma_x005bt_x005d", energisticsApiJNI.eml__TimeUom__Ma_x005bt_x005d_get());
  public final static eml__TimeUom eml__TimeUom__min_ = new eml__TimeUom("eml__TimeUom__min_", energisticsApiJNI.eml__TimeUom__min__get());
  public final static eml__TimeUom eml__TimeUom__ms = new eml__TimeUom("eml__TimeUom__ms", energisticsApiJNI.eml__TimeUom__ms_get());
  public final static eml__TimeUom eml__TimeUom__na = new eml__TimeUom("eml__TimeUom__na", energisticsApiJNI.eml__TimeUom__na_get());
  public final static eml__TimeUom eml__TimeUom__ns = new eml__TimeUom("eml__TimeUom__ns", energisticsApiJNI.eml__TimeUom__ns_get());
  public final static eml__TimeUom eml__TimeUom__ps = new eml__TimeUom("eml__TimeUom__ps", energisticsApiJNI.eml__TimeUom__ps_get());
  public final static eml__TimeUom eml__TimeUom__s = new eml__TimeUom("eml__TimeUom__s", energisticsApiJNI.eml__TimeUom__s_get());
  public final static eml__TimeUom eml__TimeUom__Ta_x005bt_x005d = new eml__TimeUom("eml__TimeUom__Ta_x005bt_x005d", energisticsApiJNI.eml__TimeUom__Ta_x005bt_x005d_get());
  public final static eml__TimeUom eml__TimeUom__us = new eml__TimeUom("eml__TimeUom__us", energisticsApiJNI.eml__TimeUom__us_get());
  public final static eml__TimeUom eml__TimeUom__wk = new eml__TimeUom("eml__TimeUom__wk", energisticsApiJNI.eml__TimeUom__wk_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static eml__TimeUom swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + eml__TimeUom.class + " with value " + swigValue);
  }

  private eml__TimeUom(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private eml__TimeUom(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private eml__TimeUom(String swigName, eml__TimeUom swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static eml__TimeUom[] swigValues = { eml__TimeUom__1_x002f2_x0020ms, eml__TimeUom__100_x0020ka_x005bt_x005d, eml__TimeUom__a, eml__TimeUom__a_x005bt_x005d, eml__TimeUom__ca, eml__TimeUom__cs, eml__TimeUom__d, eml__TimeUom__ds, eml__TimeUom__Ea_x005bt_x005d, eml__TimeUom__fa, eml__TimeUom__Ga_x005bt_x005d, eml__TimeUom__h, eml__TimeUom__hs, eml__TimeUom__ka_x005bt_x005d, eml__TimeUom__Ma_x005bt_x005d, eml__TimeUom__min_, eml__TimeUom__ms, eml__TimeUom__na, eml__TimeUom__ns, eml__TimeUom__ps, eml__TimeUom__s, eml__TimeUom__Ta_x005bt_x005d, eml__TimeUom__us, eml__TimeUom__wk };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

