/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public class FractureVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public FractureVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FractureVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        energisticsApiJNI.delete_FractureVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FractureVector() {
    this(energisticsApiJNI.new_FractureVector__SWIG_0(), true);
  }

  public FractureVector(long n) {
    this(energisticsApiJNI.new_FractureVector__SWIG_1(n), true);
  }

  public long size() {
    return energisticsApiJNI.FractureVector_size(swigCPtr, this);
  }

  public long capacity() {
    return energisticsApiJNI.FractureVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    energisticsApiJNI.FractureVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return energisticsApiJNI.FractureVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    energisticsApiJNI.FractureVector_clear(swigCPtr, this);
  }

  public void add(com.f2i.energisticsStandardsApi.resqml2_0.Fracture x) {
    energisticsApiJNI.FractureVector_add(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.Fracture.getCPtr(x), x);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.Fracture get(int i) {
    long cPtr = energisticsApiJNI.FractureVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.Fracture(cPtr, false);
  }

  public void set(int i, com.f2i.energisticsStandardsApi.resqml2_0.Fracture val) {
    energisticsApiJNI.FractureVector_set(swigCPtr, this, i, com.f2i.energisticsStandardsApi.resqml2_0.Fracture.getCPtr(val), val);
  }

}
