/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public class Grid2dRepresentationVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Grid2dRepresentationVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Grid2dRepresentationVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        energisticsApiJNI.delete_Grid2dRepresentationVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Grid2dRepresentationVector() {
    this(energisticsApiJNI.new_Grid2dRepresentationVector__SWIG_0(), true);
  }

  public Grid2dRepresentationVector(long n) {
    this(energisticsApiJNI.new_Grid2dRepresentationVector__SWIG_1(n), true);
  }

  public long size() {
    return energisticsApiJNI.Grid2dRepresentationVector_size(swigCPtr, this);
  }

  public long capacity() {
    return energisticsApiJNI.Grid2dRepresentationVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    energisticsApiJNI.Grid2dRepresentationVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return energisticsApiJNI.Grid2dRepresentationVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    energisticsApiJNI.Grid2dRepresentationVector_clear(swigCPtr, this);
  }

  public void add(com.f2i.energisticsStandardsApi.resqml2_0.Grid2dRepresentation x) {
    energisticsApiJNI.Grid2dRepresentationVector_add(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.Grid2dRepresentation.getCPtr(x), x);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.Grid2dRepresentation get(int i) {
    long cPtr = energisticsApiJNI.Grid2dRepresentationVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.Grid2dRepresentation(cPtr, false);
  }

  public void set(int i, com.f2i.energisticsStandardsApi.resqml2_0.Grid2dRepresentation val) {
    energisticsApiJNI.Grid2dRepresentationVector_set(swigCPtr, this, i, com.f2i.energisticsStandardsApi.resqml2_0.Grid2dRepresentation.getCPtr(val), val);
  }

}
