/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public class LocalDepth3dCrsVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public LocalDepth3dCrsVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(LocalDepth3dCrsVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        energisticsApiJNI.delete_LocalDepth3dCrsVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LocalDepth3dCrsVector() {
    this(energisticsApiJNI.new_LocalDepth3dCrsVector__SWIG_0(), true);
  }

  public LocalDepth3dCrsVector(long n) {
    this(energisticsApiJNI.new_LocalDepth3dCrsVector__SWIG_1(n), true);
  }

  public long size() {
    return energisticsApiJNI.LocalDepth3dCrsVector_size(swigCPtr, this);
  }

  public long capacity() {
    return energisticsApiJNI.LocalDepth3dCrsVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    energisticsApiJNI.LocalDepth3dCrsVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return energisticsApiJNI.LocalDepth3dCrsVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    energisticsApiJNI.LocalDepth3dCrsVector_clear(swigCPtr, this);
  }

  public void add(com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs x) {
    energisticsApiJNI.LocalDepth3dCrsVector_add(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs.getCPtr(x), x);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs get(int i) {
    long cPtr = energisticsApiJNI.LocalDepth3dCrsVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs(cPtr, false);
  }

  public void set(int i, com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs val) {
    energisticsApiJNI.LocalDepth3dCrsVector_set(swigCPtr, this, i, com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs.getCPtr(val), val);
  }

}
