/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public class PolylineRepresentationVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public PolylineRepresentationVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PolylineRepresentationVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        energisticsApiJNI.delete_PolylineRepresentationVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PolylineRepresentationVector() {
    this(energisticsApiJNI.new_PolylineRepresentationVector__SWIG_0(), true);
  }

  public PolylineRepresentationVector(long n) {
    this(energisticsApiJNI.new_PolylineRepresentationVector__SWIG_1(n), true);
  }

  public long size() {
    return energisticsApiJNI.PolylineRepresentationVector_size(swigCPtr, this);
  }

  public long capacity() {
    return energisticsApiJNI.PolylineRepresentationVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    energisticsApiJNI.PolylineRepresentationVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return energisticsApiJNI.PolylineRepresentationVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    energisticsApiJNI.PolylineRepresentationVector_clear(swigCPtr, this);
  }

  public void add(com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation x) {
    energisticsApiJNI.PolylineRepresentationVector_add(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation.getCPtr(x), x);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation get(int i) {
    long cPtr = energisticsApiJNI.PolylineRepresentationVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation(cPtr, false);
  }

  public void set(int i, com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation val) {
    energisticsApiJNI.PolylineRepresentationVector_set(swigCPtr, this, i, com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation.getCPtr(val), val);
  }

}
