/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public final class resqml2__GeologicBoundaryKind {
  public final static resqml2__GeologicBoundaryKind resqml2__GeologicBoundaryKind__fault = new resqml2__GeologicBoundaryKind("resqml2__GeologicBoundaryKind__fault", energisticsApiJNI.resqml2__GeologicBoundaryKind__fault_get());
  public final static resqml2__GeologicBoundaryKind resqml2__GeologicBoundaryKind__geobody = new resqml2__GeologicBoundaryKind("resqml2__GeologicBoundaryKind__geobody", energisticsApiJNI.resqml2__GeologicBoundaryKind__geobody_get());
  public final static resqml2__GeologicBoundaryKind resqml2__GeologicBoundaryKind__horizon = new resqml2__GeologicBoundaryKind("resqml2__GeologicBoundaryKind__horizon", energisticsApiJNI.resqml2__GeologicBoundaryKind__horizon_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static resqml2__GeologicBoundaryKind swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + resqml2__GeologicBoundaryKind.class + " with value " + swigValue);
  }

  private resqml2__GeologicBoundaryKind(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private resqml2__GeologicBoundaryKind(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private resqml2__GeologicBoundaryKind(String swigName, resqml2__GeologicBoundaryKind swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static resqml2__GeologicBoundaryKind[] swigValues = { resqml2__GeologicBoundaryKind__fault, resqml2__GeologicBoundaryKind__geobody, resqml2__GeologicBoundaryKind__horizon };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

