/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public class ShortArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ShortArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ShortArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        energisticsApiJNI.delete_ShortArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ShortArray(int nelements) {
    this(energisticsApiJNI.new_ShortArray(nelements), true);
  }

  public short getitem(int index) {
    return energisticsApiJNI.ShortArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, short value) {
    energisticsApiJNI.ShortArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_short cast() {
    long cPtr = energisticsApiJNI.ShortArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_short(cPtr, false);
  }

  public static ShortArray frompointer(SWIGTYPE_p_short t) {
    long cPtr = energisticsApiJNI.ShortArray_frompointer(SWIGTYPE_p_short.getCPtr(t));
    return (cPtr == 0) ? null : new ShortArray(cPtr, false);
  }

}
