/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public class StratigraphicUnitInterpretationVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public StratigraphicUnitInterpretationVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StratigraphicUnitInterpretationVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        energisticsApiJNI.delete_StratigraphicUnitInterpretationVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StratigraphicUnitInterpretationVector() {
    this(energisticsApiJNI.new_StratigraphicUnitInterpretationVector__SWIG_0(), true);
  }

  public StratigraphicUnitInterpretationVector(long n) {
    this(energisticsApiJNI.new_StratigraphicUnitInterpretationVector__SWIG_1(n), true);
  }

  public long size() {
    return energisticsApiJNI.StratigraphicUnitInterpretationVector_size(swigCPtr, this);
  }

  public long capacity() {
    return energisticsApiJNI.StratigraphicUnitInterpretationVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    energisticsApiJNI.StratigraphicUnitInterpretationVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return energisticsApiJNI.StratigraphicUnitInterpretationVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    energisticsApiJNI.StratigraphicUnitInterpretationVector_clear(swigCPtr, this);
  }

  public void add(com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitInterpretation x) {
    energisticsApiJNI.StratigraphicUnitInterpretationVector_add(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitInterpretation.getCPtr(x), x);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitInterpretation get(int i) {
    long cPtr = energisticsApiJNI.StratigraphicUnitInterpretationVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitInterpretation(cPtr, false);
  }

  public void set(int i, com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitInterpretation val) {
    energisticsApiJNI.StratigraphicUnitInterpretationVector_set(swigCPtr, this, i, com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitInterpretation.getCPtr(val), val);
  }

}
