/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public class UIntArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public UIntArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UIntArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        energisticsApiJNI.delete_UIntArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UIntArray(int nelements) {
    this(energisticsApiJNI.new_UIntArray(nelements), true);
  }

  public long getitem(int index) {
    return energisticsApiJNI.UIntArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, long value) {
    energisticsApiJNI.UIntArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_unsigned_int cast() {
    long cPtr = energisticsApiJNI.UIntArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public static UIntArray frompointer(SWIGTYPE_p_unsigned_int t) {
    long cPtr = energisticsApiJNI.UIntArray_frompointer(SWIGTYPE_p_unsigned_int.getCPtr(t));
    return (cPtr == 0) ? null : new UIntArray(cPtr, false);
  }

}
