/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public class ULongLongArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ULongLongArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ULongLongArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        energisticsApiJNI.delete_ULongLongArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ULongLongArray(int nelements) {
    this(energisticsApiJNI.new_ULongLongArray(nelements), true);
  }

  public java.math.BigInteger getitem(int index) {
    return energisticsApiJNI.ULongLongArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, java.math.BigInteger value) {
    energisticsApiJNI.ULongLongArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_unsigned_long_long cast() {
    long cPtr = energisticsApiJNI.ULongLongArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public static ULongLongArray frompointer(SWIGTYPE_p_unsigned_long_long t) {
    long cPtr = energisticsApiJNI.ULongLongArray_frompointer(SWIGTYPE_p_unsigned_long_long.getCPtr(t));
    return (cPtr == 0) ? null : new ULongLongArray(cPtr, false);
  }

}
