/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public class WellboreMarkerFrameRepresentationVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public WellboreMarkerFrameRepresentationVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(WellboreMarkerFrameRepresentationVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        energisticsApiJNI.delete_WellboreMarkerFrameRepresentationVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WellboreMarkerFrameRepresentationVector() {
    this(energisticsApiJNI.new_WellboreMarkerFrameRepresentationVector__SWIG_0(), true);
  }

  public WellboreMarkerFrameRepresentationVector(long n) {
    this(energisticsApiJNI.new_WellboreMarkerFrameRepresentationVector__SWIG_1(n), true);
  }

  public long size() {
    return energisticsApiJNI.WellboreMarkerFrameRepresentationVector_size(swigCPtr, this);
  }

  public long capacity() {
    return energisticsApiJNI.WellboreMarkerFrameRepresentationVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    energisticsApiJNI.WellboreMarkerFrameRepresentationVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return energisticsApiJNI.WellboreMarkerFrameRepresentationVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    energisticsApiJNI.WellboreMarkerFrameRepresentationVector_clear(swigCPtr, this);
  }

  public void add(com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation x) {
    energisticsApiJNI.WellboreMarkerFrameRepresentationVector_add(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation.getCPtr(x), x);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation get(int i) {
    long cPtr = energisticsApiJNI.WellboreMarkerFrameRepresentationVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation(cPtr, false);
  }

  public void set(int i, com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation val) {
    energisticsApiJNI.WellboreMarkerFrameRepresentationVector_set(swigCPtr, this, i, com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation.getCPtr(val), val);
  }

}
