/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public final class witsml1__PerLengthUom {
  public final static witsml1__PerLengthUom witsml1__PerLengthUom__1_x002fm = new witsml1__PerLengthUom("witsml1__PerLengthUom__1_x002fm", energisticsApiJNI.witsml1__PerLengthUom__1_x002fm_get());
  public final static witsml1__PerLengthUom witsml1__PerLengthUom__1_x002fangstrom = new witsml1__PerLengthUom("witsml1__PerLengthUom__1_x002fangstrom", energisticsApiJNI.witsml1__PerLengthUom__1_x002fangstrom_get());
  public final static witsml1__PerLengthUom witsml1__PerLengthUom__1_x002fcm = new witsml1__PerLengthUom("witsml1__PerLengthUom__1_x002fcm", energisticsApiJNI.witsml1__PerLengthUom__1_x002fcm_get());
  public final static witsml1__PerLengthUom witsml1__PerLengthUom__1_x002fft = new witsml1__PerLengthUom("witsml1__PerLengthUom__1_x002fft", energisticsApiJNI.witsml1__PerLengthUom__1_x002fft_get());
  public final static witsml1__PerLengthUom witsml1__PerLengthUom__1_x002fin = new witsml1__PerLengthUom("witsml1__PerLengthUom__1_x002fin", energisticsApiJNI.witsml1__PerLengthUom__1_x002fin_get());
  public final static witsml1__PerLengthUom witsml1__PerLengthUom__1_x002fmi = new witsml1__PerLengthUom("witsml1__PerLengthUom__1_x002fmi", energisticsApiJNI.witsml1__PerLengthUom__1_x002fmi_get());
  public final static witsml1__PerLengthUom witsml1__PerLengthUom__1_x002fmm = new witsml1__PerLengthUom("witsml1__PerLengthUom__1_x002fmm", energisticsApiJNI.witsml1__PerLengthUom__1_x002fmm_get());
  public final static witsml1__PerLengthUom witsml1__PerLengthUom__1_x002fnm = new witsml1__PerLengthUom("witsml1__PerLengthUom__1_x002fnm", energisticsApiJNI.witsml1__PerLengthUom__1_x002fnm_get());
  public final static witsml1__PerLengthUom witsml1__PerLengthUom__1_x002fyd = new witsml1__PerLengthUom("witsml1__PerLengthUom__1_x002fyd", energisticsApiJNI.witsml1__PerLengthUom__1_x002fyd_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static witsml1__PerLengthUom swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + witsml1__PerLengthUom.class + " with value " + swigValue);
  }

  private witsml1__PerLengthUom(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private witsml1__PerLengthUom(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private witsml1__PerLengthUom(String swigName, witsml1__PerLengthUom swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static witsml1__PerLengthUom[] swigValues = { witsml1__PerLengthUom__1_x002fm, witsml1__PerLengthUom__1_x002fangstrom, witsml1__PerLengthUom__1_x002fcm, witsml1__PerLengthUom__1_x002fft, witsml1__PerLengthUom__1_x002fin, witsml1__PerLengthUom__1_x002fmi, witsml1__PerLengthUom__1_x002fmm, witsml1__PerLengthUom__1_x002fnm, witsml1__PerLengthUom__1_x002fyd };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

