/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public final class witsml1__WellVerticalCoordinateUom {
  public final static witsml1__WellVerticalCoordinateUom witsml1__WellVerticalCoordinateUom__m = new witsml1__WellVerticalCoordinateUom("witsml1__WellVerticalCoordinateUom__m", energisticsApiJNI.witsml1__WellVerticalCoordinateUom__m_get());
  public final static witsml1__WellVerticalCoordinateUom witsml1__WellVerticalCoordinateUom__ft = new witsml1__WellVerticalCoordinateUom("witsml1__WellVerticalCoordinateUom__ft", energisticsApiJNI.witsml1__WellVerticalCoordinateUom__ft_get());
  public final static witsml1__WellVerticalCoordinateUom witsml1__WellVerticalCoordinateUom__ftUS = new witsml1__WellVerticalCoordinateUom("witsml1__WellVerticalCoordinateUom__ftUS", energisticsApiJNI.witsml1__WellVerticalCoordinateUom__ftUS_get());
  public final static witsml1__WellVerticalCoordinateUom witsml1__WellVerticalCoordinateUom__ftBr_x002865_x0029 = new witsml1__WellVerticalCoordinateUom("witsml1__WellVerticalCoordinateUom__ftBr_x002865_x0029", energisticsApiJNI.witsml1__WellVerticalCoordinateUom__ftBr_x002865_x0029_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static witsml1__WellVerticalCoordinateUom swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + witsml1__WellVerticalCoordinateUom.class + " with value " + swigValue);
  }

  private witsml1__WellVerticalCoordinateUom(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private witsml1__WellVerticalCoordinateUom(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private witsml1__WellVerticalCoordinateUom(String swigName, witsml1__WellVerticalCoordinateUom swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static witsml1__WellVerticalCoordinateUom[] swigValues = { witsml1__WellVerticalCoordinateUom__m, witsml1__WellVerticalCoordinateUom__ft, witsml1__WellVerticalCoordinateUom__ftUS, witsml1__WellVerticalCoordinateUom__ftBr_x002865_x0029 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

