/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public final class witsml1__WellStatus {
  public final static witsml1__WellStatus witsml1__WellStatus__abandoned = new witsml1__WellStatus("witsml1__WellStatus__abandoned", energisticsApiJNI.witsml1__WellStatus__abandoned_get());
  public final static witsml1__WellStatus witsml1__WellStatus__active = new witsml1__WellStatus("witsml1__WellStatus__active", energisticsApiJNI.witsml1__WellStatus__active_get());
  public final static witsml1__WellStatus witsml1__WellStatus__active_x0020_x002d__x0020injecting = new witsml1__WellStatus("witsml1__WellStatus__active_x0020_x002d__x0020injecting", energisticsApiJNI.witsml1__WellStatus__active_x0020_x002d__x0020injecting_get());
  public final static witsml1__WellStatus witsml1__WellStatus__active_x0020_x002d__x0020producing = new witsml1__WellStatus("witsml1__WellStatus__active_x0020_x002d__x0020producing", energisticsApiJNI.witsml1__WellStatus__active_x0020_x002d__x0020producing_get());
  public final static witsml1__WellStatus witsml1__WellStatus__completed = new witsml1__WellStatus("witsml1__WellStatus__completed", energisticsApiJNI.witsml1__WellStatus__completed_get());
  public final static witsml1__WellStatus witsml1__WellStatus__drilling = new witsml1__WellStatus("witsml1__WellStatus__drilling", energisticsApiJNI.witsml1__WellStatus__drilling_get());
  public final static witsml1__WellStatus witsml1__WellStatus__partially_x0020plugged = new witsml1__WellStatus("witsml1__WellStatus__partially_x0020plugged", energisticsApiJNI.witsml1__WellStatus__partially_x0020plugged_get());
  public final static witsml1__WellStatus witsml1__WellStatus__permitted = new witsml1__WellStatus("witsml1__WellStatus__permitted", energisticsApiJNI.witsml1__WellStatus__permitted_get());
  public final static witsml1__WellStatus witsml1__WellStatus__plugged_x0020and_x0020abandoned = new witsml1__WellStatus("witsml1__WellStatus__plugged_x0020and_x0020abandoned", energisticsApiJNI.witsml1__WellStatus__plugged_x0020and_x0020abandoned_get());
  public final static witsml1__WellStatus witsml1__WellStatus__proposed = new witsml1__WellStatus("witsml1__WellStatus__proposed", energisticsApiJNI.witsml1__WellStatus__proposed_get());
  public final static witsml1__WellStatus witsml1__WellStatus__sold = new witsml1__WellStatus("witsml1__WellStatus__sold", energisticsApiJNI.witsml1__WellStatus__sold_get());
  public final static witsml1__WellStatus witsml1__WellStatus__suspended = new witsml1__WellStatus("witsml1__WellStatus__suspended", energisticsApiJNI.witsml1__WellStatus__suspended_get());
  public final static witsml1__WellStatus witsml1__WellStatus__temporarily_x0020abandoned = new witsml1__WellStatus("witsml1__WellStatus__temporarily_x0020abandoned", energisticsApiJNI.witsml1__WellStatus__temporarily_x0020abandoned_get());
  public final static witsml1__WellStatus witsml1__WellStatus__testing = new witsml1__WellStatus("witsml1__WellStatus__testing", energisticsApiJNI.witsml1__WellStatus__testing_get());
  public final static witsml1__WellStatus witsml1__WellStatus__tight = new witsml1__WellStatus("witsml1__WellStatus__tight", energisticsApiJNI.witsml1__WellStatus__tight_get());
  public final static witsml1__WellStatus witsml1__WellStatus__working_x0020over = new witsml1__WellStatus("witsml1__WellStatus__working_x0020over", energisticsApiJNI.witsml1__WellStatus__working_x0020over_get());
  public final static witsml1__WellStatus witsml1__WellStatus__unknown = new witsml1__WellStatus("witsml1__WellStatus__unknown", energisticsApiJNI.witsml1__WellStatus__unknown_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static witsml1__WellStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + witsml1__WellStatus.class + " with value " + swigValue);
  }

  private witsml1__WellStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private witsml1__WellStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private witsml1__WellStatus(String swigName, witsml1__WellStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static witsml1__WellStatus[] swigValues = { witsml1__WellStatus__abandoned, witsml1__WellStatus__active, witsml1__WellStatus__active_x0020_x002d__x0020injecting, witsml1__WellStatus__active_x0020_x002d__x0020producing, witsml1__WellStatus__completed, witsml1__WellStatus__drilling, witsml1__WellStatus__partially_x0020plugged, witsml1__WellStatus__permitted, witsml1__WellStatus__plugged_x0020and_x0020abandoned, witsml1__WellStatus__proposed, witsml1__WellStatus__sold, witsml1__WellStatus__suspended, witsml1__WellStatus__temporarily_x0020abandoned, witsml1__WellStatus__testing, witsml1__WellStatus__tight, witsml1__WellStatus__working_x0020over, witsml1__WellStatus__unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

