/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public final class witsml1__LogTraceOrigin {
  public final static witsml1__LogTraceOrigin witsml1__LogTraceOrigin__realtime = new witsml1__LogTraceOrigin("witsml1__LogTraceOrigin__realtime", energisticsApiJNI.witsml1__LogTraceOrigin__realtime_get());
  public final static witsml1__LogTraceOrigin witsml1__LogTraceOrigin__modeled = new witsml1__LogTraceOrigin("witsml1__LogTraceOrigin__modeled", energisticsApiJNI.witsml1__LogTraceOrigin__modeled_get());
  public final static witsml1__LogTraceOrigin witsml1__LogTraceOrigin__unknown = new witsml1__LogTraceOrigin("witsml1__LogTraceOrigin__unknown", energisticsApiJNI.witsml1__LogTraceOrigin__unknown_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static witsml1__LogTraceOrigin swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + witsml1__LogTraceOrigin.class + " with value " + swigValue);
  }

  private witsml1__LogTraceOrigin(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private witsml1__LogTraceOrigin(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private witsml1__LogTraceOrigin(String swigName, witsml1__LogTraceOrigin swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static witsml1__LogTraceOrigin[] swigValues = { witsml1__LogTraceOrigin__realtime, witsml1__LogTraceOrigin__modeled, witsml1__LogTraceOrigin__unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

