/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public final class witsml1__MeasuredDepthUom {
  public final static witsml1__MeasuredDepthUom witsml1__MeasuredDepthUom__m = new witsml1__MeasuredDepthUom("witsml1__MeasuredDepthUom__m", energisticsApiJNI.witsml1__MeasuredDepthUom__m_get());
  public final static witsml1__MeasuredDepthUom witsml1__MeasuredDepthUom__ft = new witsml1__MeasuredDepthUom("witsml1__MeasuredDepthUom__ft", energisticsApiJNI.witsml1__MeasuredDepthUom__ft_get());
  public final static witsml1__MeasuredDepthUom witsml1__MeasuredDepthUom__ftUS = new witsml1__MeasuredDepthUom("witsml1__MeasuredDepthUom__ftUS", energisticsApiJNI.witsml1__MeasuredDepthUom__ftUS_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static witsml1__MeasuredDepthUom swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + witsml1__MeasuredDepthUom.class + " with value " + swigValue);
  }

  private witsml1__MeasuredDepthUom(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private witsml1__MeasuredDepthUom(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private witsml1__MeasuredDepthUom(String swigName, witsml1__MeasuredDepthUom swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static witsml1__MeasuredDepthUom[] swigValues = { witsml1__MeasuredDepthUom__m, witsml1__MeasuredDepthUom__ft, witsml1__MeasuredDepthUom__ftUS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

