/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public final class witsml1__WellboreType {
  public final static witsml1__WellboreType witsml1__WellboreType__bypass = new witsml1__WellboreType("witsml1__WellboreType__bypass", energisticsApiJNI.witsml1__WellboreType__bypass_get());
  public final static witsml1__WellboreType witsml1__WellboreType__initial = new witsml1__WellboreType("witsml1__WellboreType__initial", energisticsApiJNI.witsml1__WellboreType__initial_get());
  public final static witsml1__WellboreType witsml1__WellboreType__redrill = new witsml1__WellboreType("witsml1__WellboreType__redrill", energisticsApiJNI.witsml1__WellboreType__redrill_get());
  public final static witsml1__WellboreType witsml1__WellboreType__reentry = new witsml1__WellboreType("witsml1__WellboreType__reentry", energisticsApiJNI.witsml1__WellboreType__reentry_get());
  public final static witsml1__WellboreType witsml1__WellboreType__respud = new witsml1__WellboreType("witsml1__WellboreType__respud", energisticsApiJNI.witsml1__WellboreType__respud_get());
  public final static witsml1__WellboreType witsml1__WellboreType__sidetrack = new witsml1__WellboreType("witsml1__WellboreType__sidetrack", energisticsApiJNI.witsml1__WellboreType__sidetrack_get());
  public final static witsml1__WellboreType witsml1__WellboreType__unknown = new witsml1__WellboreType("witsml1__WellboreType__unknown", energisticsApiJNI.witsml1__WellboreType__unknown_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static witsml1__WellboreType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + witsml1__WellboreType.class + " with value " + swigValue);
  }

  private witsml1__WellboreType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private witsml1__WellboreType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private witsml1__WellboreType(String swigName, witsml1__WellboreType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static witsml1__WellboreType[] swigValues = { witsml1__WellboreType__bypass, witsml1__WellboreType__initial, witsml1__WellboreType__redrill, witsml1__WellboreType__reentry, witsml1__WellboreType__respud, witsml1__WellboreType__sidetrack, witsml1__WellboreType__unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

