/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi;

public final class witsml1__LogIndexType {
  public final static witsml1__LogIndexType witsml1__LogIndexType__date_x0020time = new witsml1__LogIndexType("witsml1__LogIndexType__date_x0020time", energisticsApiJNI.witsml1__LogIndexType__date_x0020time_get());
  public final static witsml1__LogIndexType witsml1__LogIndexType__elapsed_x0020time = new witsml1__LogIndexType("witsml1__LogIndexType__elapsed_x0020time", energisticsApiJNI.witsml1__LogIndexType__elapsed_x0020time_get());
  public final static witsml1__LogIndexType witsml1__LogIndexType__length = new witsml1__LogIndexType("witsml1__LogIndexType__length", energisticsApiJNI.witsml1__LogIndexType__length_get());
  public final static witsml1__LogIndexType witsml1__LogIndexType__measured_x0020depth = new witsml1__LogIndexType("witsml1__LogIndexType__measured_x0020depth", energisticsApiJNI.witsml1__LogIndexType__measured_x0020depth_get());
  public final static witsml1__LogIndexType witsml1__LogIndexType__vertical_x0020depth = new witsml1__LogIndexType("witsml1__LogIndexType__vertical_x0020depth", energisticsApiJNI.witsml1__LogIndexType__vertical_x0020depth_get());
  public final static witsml1__LogIndexType witsml1__LogIndexType__other = new witsml1__LogIndexType("witsml1__LogIndexType__other", energisticsApiJNI.witsml1__LogIndexType__other_get());
  public final static witsml1__LogIndexType witsml1__LogIndexType__unknown = new witsml1__LogIndexType("witsml1__LogIndexType__unknown", energisticsApiJNI.witsml1__LogIndexType__unknown_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static witsml1__LogIndexType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + witsml1__LogIndexType.class + " with value " + swigValue);
  }

  private witsml1__LogIndexType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private witsml1__LogIndexType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private witsml1__LogIndexType(String swigName, witsml1__LogIndexType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static witsml1__LogIndexType[] swigValues = { witsml1__LogIndexType__date_x0020time, witsml1__LogIndexType__elapsed_x0020time, witsml1__LogIndexType__length, witsml1__LogIndexType__measured_x0020depth, witsml1__LogIndexType__vertical_x0020depth, witsml1__LogIndexType__other, witsml1__LogIndexType__unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

