/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.f2i.energisticsStandardsApi.common;

		import com.f2i.energisticsStandardsApi.*;
	
public class EpcDocument {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public EpcDocument(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(EpcDocument obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.f2i.energisticsStandardsApi.energisticsApiJNI.delete_common_EpcDocument(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EpcDocument(String fileName) {
    this(com.f2i.energisticsStandardsApi.energisticsApiJNI.new_common_EpcDocument__SWIG_0(fileName), true);
  }

  public EpcDocument(String fileName, String propertyKindMappingFilesDirectory) {
    this(com.f2i.energisticsStandardsApi.energisticsApiJNI.new_common_EpcDocument__SWIG_1(fileName, propertyKindMappingFilesDirectory), true);
  }

  public void serialize() {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_serialize(swigCPtr, this);
  }

  public String deserialize() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_deserialize(swigCPtr, this);
  }

  public void close() {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_close(swigCPtr, this);
  }

  public String getStorageDirectory() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getStorageDirectory(swigCPtr, this);
  }

  public String getName() {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getName(swigCPtr, this);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PropertyKindMapper getPropertyKindMapper() {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getPropertyKindMapper(swigCPtr, this);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PropertyKindMapper(cPtr, false);
  }

  public resqml2__ResqmlUom getResqmlUnitOfMeasure(String uomName) {
    return resqml2__ResqmlUom.swigToEnum(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getResqmlUnitOfMeasure(swigCPtr, this, uomName));
  }

  public String getResqmlStandardPropertyKindName(resqml2__ResqmlPropertyKind resqmlStandardPropertyKindName) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getResqmlStandardPropertyKindName(swigCPtr, this, resqmlStandardPropertyKindName.swigValue());
  }

  public String getWitsmlLengthUom(witsml1__LengthUom witsmlUom) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getWitsmlLengthUom(swigCPtr, this, witsmlUom.swigValue());
  }

  public String getWitsmlWellVerticalCoordinateUom(witsml1__WellVerticalCoordinateUom witsmlUom) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getWitsmlWellVerticalCoordinateUom(swigCPtr, this, witsmlUom.swigValue());
  }

  public String getWitsmlMeasuredDepthUom(witsml1__MeasuredDepthUom witsmlUom) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getWitsmlMeasuredDepthUom(swigCPtr, this, witsmlUom.swigValue());
  }

  public String getWitsmlPlaneAngleUom(witsml1__PlaneAngleUom witsmlUom) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getWitsmlPlaneAngleUom(swigCPtr, this, witsmlUom.swigValue());
  }

  public LocalDepth3dCrsVector getLocalDepth3dCrsSet() {
    return new LocalDepth3dCrsVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getLocalDepth3dCrsSet(swigCPtr, this), false);
  }

  public LocalTime3dCrsVector getLocalTime3dCrsSet() {
    return new LocalTime3dCrsVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getLocalTime3dCrsSet(swigCPtr, this), false);
  }

  public StratigraphicColumnVector getStratigraphicColumnSet() {
    return new StratigraphicColumnVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getStratigraphicColumnSet(swigCPtr, this), false);
  }

  public FaultVector getFaultSet() {
    return new FaultVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getFaultSet(swigCPtr, this), false);
  }

  public FractureVector getFractureSet() {
    return new FractureVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getFractureSet(swigCPtr, this), false);
  }

  public PolylineSetRepresentationVector getFaultPolylineSetRepSet() {
    return new PolylineSetRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getFaultPolylineSetRepSet(swigCPtr, this), true);
  }

  public PolylineSetRepresentationVector getFracturePolylineSetRepSet() {
    return new PolylineSetRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getFracturePolylineSetRepSet(swigCPtr, this), true);
  }

  public TriangulatedSetRepresentationVector getFaultTriangulatedSetRepSet() {
    return new TriangulatedSetRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getFaultTriangulatedSetRepSet(swigCPtr, this), true);
  }

  public TriangulatedSetRepresentationVector getFractureTriangulatedSetRepSet() {
    return new TriangulatedSetRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getFractureTriangulatedSetRepSet(swigCPtr, this), true);
  }

  public HorizonVector getHorizonSet() {
    return new HorizonVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getHorizonSet(swigCPtr, this), false);
  }

  public Grid2dSetRepresentationVector getHorizonGrid2dSetRepSet() {
    return new Grid2dSetRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getHorizonGrid2dSetRepSet(swigCPtr, this), true);
  }

  public Grid2dRepresentationVector getHorizonGrid2dRepSet() {
    return new Grid2dRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getHorizonGrid2dRepSet(swigCPtr, this), true);
  }

  public PolylineRepresentationVector getHorizonPolylineRepSet() {
    return new PolylineRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getHorizonPolylineRepSet(swigCPtr, this), true);
  }

  public PolylineSetRepresentationVector getHorizonPolylineSetRepSet() {
    return new PolylineSetRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getHorizonPolylineSetRepSet(swigCPtr, this), true);
  }

  public TriangulatedSetRepresentationVector getHorizonTriangulatedSetRepSet() {
    return new TriangulatedSetRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getHorizonTriangulatedSetRepSet(swigCPtr, this), true);
  }

  public TriangulatedSetRepresentationVector getAllTriangulatedSetRepSet() {
    return new TriangulatedSetRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getAllTriangulatedSetRepSet(swigCPtr, this), false);
  }

  public TriangulatedSetRepresentationVector getUnclassifiedTriangulatedSetRepSet() {
    return new TriangulatedSetRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getUnclassifiedTriangulatedSetRepSet(swigCPtr, this), true);
  }

  public SeismicLineFeatureVector getSeismicLineSet() {
    return new SeismicLineFeatureVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getSeismicLineSet(swigCPtr, this), true);
  }

  public WellboreFeatureVector getWellboreSet() {
    return new WellboreFeatureVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getWellboreSet(swigCPtr, this), true);
  }

  public WellboreTrajectoryRepresentationVector getWellboreCubicParamLineTrajRepSet() {
    return new WellboreTrajectoryRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getWellboreCubicParamLineTrajRepSet(swigCPtr, this), true);
  }

  public HdfProxyVector getHdfProxySet() {
    return new HdfProxyVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getHdfProxySet(swigCPtr, this), true);
  }

  public IjkGridRepresentationVector getIjkGridRepresentationSet() {
    return new IjkGridRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getIjkGridRepresentationSet(swigCPtr, this), true);
  }

  public IjkGridRepresentationVector getIjkParametricGridRepresentationSet() {
    return new IjkGridRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getIjkParametricGridRepresentationSet(swigCPtr, this), true);
  }

  public IjkGridRepresentationVector getIjkSeismicCubeGridRepresentationSet() {
    return new IjkGridRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getIjkSeismicCubeGridRepresentationSet(swigCPtr, this), true);
  }

  public UnstructuredGridRepresentationVector getUnstructuredGridRepresentationSet() {
    return new UnstructuredGridRepresentationVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getUnstructuredGridRepresentationSet(swigCPtr, this), true);
  }

  public void setExtendedCoreProperty(String key, String value) {
    com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_setExtendedCoreProperty(swigCPtr, this, key, value);
  }

  public String getExtendedCoreProperty(String key) {
    return com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getExtendedCoreProperty(swigCPtr, this, key);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.AbstractObject getResqmlAbstractObjectByUuid(String uuid) {
		long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getResqmlAbstractObjectByUuid(swigCPtr, this, uuid);
		com.f2i.energisticsStandardsApi.resqml2_0.AbstractObject ret = (com.f2i.energisticsStandardsApi.resqml2_0.AbstractObject) energisticsApiJNI.resqml2_0_instantiateConcreteObject(cPtr, false);
		return ret;
	}

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.AbstractObject getWitsmlAbstractObjectByUuid(String uuid) {
		long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getWitsmlAbstractObjectByUuid(swigCPtr, this, uuid);
		com.f2i.energisticsStandardsApi.witsml1_4_1_1.AbstractObject ret = (com.f2i.energisticsStandardsApi.witsml1_4_1_1.AbstractObject) energisticsApiJNI.witsml1_4_1_1_instantiateConcreteObject(cPtr, false);
		return ret;
	}

  public com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy createHdfProxy(String guid, String title, String packageDirAbsolutePath, String externalFilePath) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createHdfProxy(swigCPtr, this, guid, title, packageDirAbsolutePath, externalFilePath);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.HdfProxy(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs createLocalDepth3dCrs(String guid, String title, double originOrdinal1, double originOrdinal2, double originOrdinal3, double arealRotation, eml__LengthUom projectedUom, long projectedEpsgCode, eml__LengthUom verticalUom, boolean isUpOriented, long epsgCode) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createLocalDepth3dCrs__SWIG_0(swigCPtr, this, guid, title, originOrdinal1, originOrdinal2, originOrdinal3, arealRotation, projectedUom.swigValue(), projectedEpsgCode, verticalUom.swigValue(), isUpOriented, epsgCode);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs createLocalDepth3dCrs(String guid, String title, double originOrdinal1, double originOrdinal2, double originOrdinal3, double arealRotation, eml__LengthUom projectedUom, long projectedEpsgCode, eml__LengthUom verticalUom, boolean isUpOriented) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createLocalDepth3dCrs__SWIG_1(swigCPtr, this, guid, title, originOrdinal1, originOrdinal2, originOrdinal3, arealRotation, projectedUom.swigValue(), projectedEpsgCode, verticalUom.swigValue(), isUpOriented);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs createLocalDepth3dCrs(String guid, String title, double originOrdinal1, double originOrdinal2, double originOrdinal3, double arealRotation, eml__LengthUom projectedUom, long projectedEpsgCode, eml__LengthUom verticalUom) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createLocalDepth3dCrs__SWIG_2(swigCPtr, this, guid, title, originOrdinal1, originOrdinal2, originOrdinal3, arealRotation, projectedUom.swigValue(), projectedEpsgCode, verticalUom.swigValue());
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.LocalDepth3dCrs(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.LocalTime3dCrs createLocalTime3dCrs(String guid, String title, double originOrdinal1, double originOrdinal2, double originOrdinal3, double arealRotation, eml__LengthUom projectedUom, long projectedEpsgCode, eml__TimeUom timeUom, eml__LengthUom verticalUom, boolean isUpOriented, long epsgCode) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createLocalTime3dCrs__SWIG_0(swigCPtr, this, guid, title, originOrdinal1, originOrdinal2, originOrdinal3, arealRotation, projectedUom.swigValue(), projectedEpsgCode, timeUom.swigValue(), verticalUom.swigValue(), isUpOriented, epsgCode);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.LocalTime3dCrs(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.LocalTime3dCrs createLocalTime3dCrs(String guid, String title, double originOrdinal1, double originOrdinal2, double originOrdinal3, double arealRotation, eml__LengthUom projectedUom, long projectedEpsgCode, eml__TimeUom timeUom, eml__LengthUom verticalUom, boolean isUpOriented) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createLocalTime3dCrs__SWIG_1(swigCPtr, this, guid, title, originOrdinal1, originOrdinal2, originOrdinal3, arealRotation, projectedUom.swigValue(), projectedEpsgCode, timeUom.swigValue(), verticalUom.swigValue(), isUpOriented);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.LocalTime3dCrs(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.LocalTime3dCrs createLocalTime3dCrs(String guid, String title, double originOrdinal1, double originOrdinal2, double originOrdinal3, double arealRotation, eml__LengthUom projectedUom, long projectedEpsgCode, eml__TimeUom timeUom, eml__LengthUom verticalUom) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createLocalTime3dCrs__SWIG_2(swigCPtr, this, guid, title, originOrdinal1, originOrdinal2, originOrdinal3, arealRotation, projectedUom.swigValue(), projectedEpsgCode, timeUom.swigValue(), verticalUom.swigValue());
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.LocalTime3dCrs(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.MdDatum createMdDatum(String guid, String title, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs locCrs, resqml2__MdReference originKind, double referenceLocationOrdinal1, double referenceLocationOrdinal2, double referenceLocationOrdinal3) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createMdDatum(swigCPtr, this, guid, title, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(locCrs), locCrs, originKind.swigValue(), referenceLocationOrdinal1, referenceLocationOrdinal2, referenceLocationOrdinal3);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.MdDatum(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.BoundaryFeature createBoundaryFeature(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createBoundaryFeature(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.BoundaryFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.Horizon createHorizon(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createHorizon(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.Horizon(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.TectonicBoundaryFeature createTectonicBoundaryFeature(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createTectonicBoundaryFeature(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.TectonicBoundaryFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.Fault createFault(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createFault(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.Fault(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.Fracture createFracture(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createFracture(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.Fracture(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.WellboreFeature createWellboreFeature(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createWellboreFeature(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.WellboreFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.SeismicLatticeFeature createSeismicLattice(String guid, String title, int inlineIncrement, int crosslineIncrement, long originInline, long originCrossline, long inlineCount, long crosslineCount) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createSeismicLattice(swigCPtr, this, guid, title, inlineIncrement, crosslineIncrement, originInline, originCrossline, inlineCount, crosslineCount);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.SeismicLatticeFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.SeismicLineFeature createSeismicLine(String guid, String title, int traceIndexIncrement, long firstTraceIndex, long traceCount) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createSeismicLine(swigCPtr, this, guid, title, traceIndexIncrement, firstTraceIndex, traceCount);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.SeismicLineFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.SeismicLineSetFeature createSeismicLineSet(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createSeismicLineSet(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.SeismicLineSetFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.FrontierFeature createFrontier(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createFrontier(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.FrontierFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature createStructuralModel(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStructuralModel(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitFeature createStratigraphicUnit(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStratigraphicUnit(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature createStratigraphicModel(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStratigraphicModel(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature createEarthModel(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createEarthModel(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.FluidBoundaryFeature createFluidBoundaryFeature(String guid, String title, resqml2__FluidContact fluidContact) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createFluidBoundaryFeature(swigCPtr, this, guid, title, fluidContact.swigValue());
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.FluidBoundaryFeature(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.GenericFeatureInterpretation createGenericFeatureInterpretation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeature feature, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createGenericFeatureInterpretation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeature.getCPtr(feature), feature, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.GenericFeatureInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.BoundaryFeatureInterpretation createBoundaryFeatureInterpretation(com.f2i.energisticsStandardsApi.resqml2_0.BoundaryFeature feature, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createBoundaryFeatureInterpretation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.BoundaryFeature.getCPtr(feature), feature, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.BoundaryFeatureInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.HorizonInterpretation createHorizonInterpretation(com.f2i.energisticsStandardsApi.resqml2_0.Horizon horizon, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createHorizonInterpretation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.Horizon.getCPtr(horizon), horizon, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.HorizonInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.FaultInterpretation createFaultInterpretation(com.f2i.energisticsStandardsApi.resqml2_0.Fault fault, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createFaultInterpretation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.Fault.getCPtr(fault), fault, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.FaultInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.WellboreInterpretation createWellboreInterpretation(com.f2i.energisticsStandardsApi.resqml2_0.WellboreFeature wellbore, String guid, String title, boolean isDrilled) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createWellboreInterpretation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.WellboreFeature.getCPtr(wellbore), wellbore, guid, title, isDrilled);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.WellboreInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.EarthModelInterpretation createEarthModelInterpretation(com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature orgFeat, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createEarthModelInterpretation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature.getCPtr(orgFeat), orgFeat, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.EarthModelInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StructuralOrganizationInterpretation createStructuralOrganizationInterpretationInAge(com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature orgFeat, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStructuralOrganizationInterpretationInAge(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature.getCPtr(orgFeat), orgFeat, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StructuralOrganizationInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StructuralOrganizationInterpretation createStructuralOrganizationInterpretationInApparentDepth(com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature orgFeat, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStructuralOrganizationInterpretationInApparentDepth(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature.getCPtr(orgFeat), orgFeat, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StructuralOrganizationInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StructuralOrganizationInterpretation createStructuralOrganizationInterpretationInMeasuredDepth(com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature orgFeat, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStructuralOrganizationInterpretationInMeasuredDepth(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature.getCPtr(orgFeat), orgFeat, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StructuralOrganizationInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitInterpretation createStratigraphicUnitInterpretation(com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitFeature stratiUnitFeature, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStratigraphicUnitInterpretation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitFeature.getCPtr(stratiUnitFeature), stratiUnitFeature, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicUnitInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumn createStratigraphicColumn(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStratigraphicColumn(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumn(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumnRankInterpretation createStratigraphicColumnRankInterpretationInAge(com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature orgFeat, String guid, String title, long rank) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStratigraphicColumnRankInterpretationInAge(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature.getCPtr(orgFeat), orgFeat, guid, title, rank);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumnRankInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumnRankInterpretation createStratigraphicColumnRankInterpretationInApparentDepth(com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature orgFeat, String guid, String title, long rank) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStratigraphicColumnRankInterpretationInApparentDepth(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature.getCPtr(orgFeat), orgFeat, guid, title, rank);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumnRankInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicOccurrenceInterpretation createStratigraphicOccurrenceInterpretationInAge(com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature orgFeat, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStratigraphicOccurrenceInterpretationInAge(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature.getCPtr(orgFeat), orgFeat, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicOccurrenceInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicOccurrenceInterpretation createStratigraphicOccurrenceInterpretationInApparentDepth(com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature orgFeat, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStratigraphicOccurrenceInterpretationInApparentDepth(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.OrganizationFeature.getCPtr(orgFeat), orgFeat, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicOccurrenceInterpretation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.TriangulatedSetRepresentation createTriangulatedSetRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createTriangulatedSetRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.TriangulatedSetRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PolylineSetRepresentation createPolylineSetRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createPolylineSetRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PolylineSetRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PointSetRepresentation createPointSetRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createPointSetRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PointSetRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PlaneSetRepresentation createPlaneSetRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createPlaneSetRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PlaneSetRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation createPolylineRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title, boolean isClosed) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createPolylineRepresentation__SWIG_0(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title, isClosed);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation createPolylineRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createPolylineRepresentation__SWIG_1(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation createPolylineRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title, resqml2__LineRole roleKind, boolean isClosed) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createPolylineRepresentation__SWIG_2(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title, roleKind.swigValue(), isClosed);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation createPolylineRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title, resqml2__LineRole roleKind) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createPolylineRepresentation__SWIG_3(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title, roleKind.swigValue());
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PolylineRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.Grid2dRepresentation createGrid2dRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createGrid2dRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.Grid2dRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.WellboreTrajectoryRepresentation createWellboreTrajectoryRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.WellboreInterpretation interp, String guid, String title, com.f2i.energisticsStandardsApi.resqml2_0.MdDatum mdInfo) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createWellboreTrajectoryRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.WellboreInterpretation.getCPtr(interp), interp, guid, title, com.f2i.energisticsStandardsApi.resqml2_0.MdDatum.getCPtr(mdInfo), mdInfo);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.WellboreTrajectoryRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.WellboreFrameRepresentation createWellboreFrameRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.WellboreInterpretation interp, String guid, String title, com.f2i.energisticsStandardsApi.resqml2_0.WellboreTrajectoryRepresentation traj) {
		long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createWellboreFrameRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.WellboreInterpretation.getCPtr(interp), interp, guid, title, com.f2i.energisticsStandardsApi.resqml2_0.WellboreTrajectoryRepresentation.getCPtr(traj), traj);
		com.f2i.energisticsStandardsApi.resqml2_0.WellboreFrameRepresentation ret = (com.f2i.energisticsStandardsApi.resqml2_0.WellboreFrameRepresentation) energisticsApiJNI.resqml2_0_instantiateWellboreFrameRepresentationObject(cPtr, false);
		return ret;
	}

  public com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation createWellboreMarkerFrameRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.WellboreInterpretation interp, String guid, String title, com.f2i.energisticsStandardsApi.resqml2_0.WellboreTrajectoryRepresentation traj) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createWellboreMarkerFrameRepresentation__SWIG_0(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.WellboreInterpretation.getCPtr(interp), interp, guid, title, com.f2i.energisticsStandardsApi.resqml2_0.WellboreTrajectoryRepresentation.getCPtr(traj), traj);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation createWellboreMarkerFrameRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumnRankInterpretation interp, String guid, String title, com.f2i.energisticsStandardsApi.resqml2_0.WellboreTrajectoryRepresentation traj) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createWellboreMarkerFrameRepresentation__SWIG_1(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicColumnRankInterpretation.getCPtr(interp), interp, guid, title, com.f2i.energisticsStandardsApi.resqml2_0.WellboreTrajectoryRepresentation.getCPtr(traj), traj);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation createWellboreMarkerFrameRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicOccurrenceInterpretation interp, String guid, String title, com.f2i.energisticsStandardsApi.resqml2_0.WellboreTrajectoryRepresentation traj) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createWellboreMarkerFrameRepresentation__SWIG_2(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.StratigraphicOccurrenceInterpretation.getCPtr(interp), interp, guid, title, com.f2i.energisticsStandardsApi.resqml2_0.WellboreTrajectoryRepresentation.getCPtr(traj), traj);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.WellboreMarkerFrameRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.RepresentationSetRepresentation createRepresentationSetRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractOrganizationInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createRepresentationSetRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractOrganizationInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.RepresentationSetRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.NonSealedSurfaceFrameworkRepresentation createNonSealedSurfaceFrameworkRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.StructuralOrganizationInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title, boolean isSealed) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createNonSealedSurfaceFrameworkRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.StructuralOrganizationInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title, isSealed);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.NonSealedSurfaceFrameworkRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.SealedSurfaceFrameworkRepresentation createSealedSurfaceFrameworkRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.StructuralOrganizationInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createSealedSurfaceFrameworkRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.StructuralOrganizationInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.SealedSurfaceFrameworkRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.IjkGridRepresentation createIjkGridRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title, long iCount, long jCount, long kCount) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createIjkGridRepresentation__SWIG_0(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title, iCount, jCount, kCount);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.IjkGridRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.IjkGridRepresentation createIjkGridRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title, long iCount, long jCount, long kCount) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createIjkGridRepresentation__SWIG_1(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title, iCount, jCount, kCount);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.IjkGridRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.UnstructuredGridRepresentation createUnstructuredGridRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title, long cellCount) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createUnstructuredGridRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title, cellCount);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.UnstructuredGridRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.SubRepresentation createSubRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation supportingRep) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createSubRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(supportingRep), supportingRep);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.SubRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.GridConnectionSetRepresentation createGridConnectionSetRepresentation(com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs crs, String guid, String title, com.f2i.energisticsStandardsApi.resqml2_0.AbstractGridRepresentation supportingGridRep) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createGridConnectionSetRepresentation(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractFeatureInterpretation.getCPtr(interp), interp, com.f2i.energisticsStandardsApi.resqml2_0.AbstractLocal3dCrs.getCPtr(crs), crs, guid, title, com.f2i.energisticsStandardsApi.resqml2_0.AbstractGridRepresentation.getCPtr(supportingGridRep), supportingGridRep);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.GridConnectionSetRepresentation(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.TimeSeries createTimeSeries(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createTimeSeries(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.TimeSeries(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.StringTableLookup createStringTableLookup(String guid, String title) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createStringTableLookup(swigCPtr, this, guid, title);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.StringTableLookup(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind createPropertyKind(String guid, String title, String namingSystem, resqml2__ResqmlUom uom, resqml2__ResqmlPropertyKind parentEnergisticsPropertyKind) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createPropertyKind__SWIG_0(swigCPtr, this, guid, title, namingSystem, uom.swigValue(), parentEnergisticsPropertyKind.swigValue());
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind createPropertyKind(String guid, String title, String namingSystem, resqml2__ResqmlUom uom, com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind parentPropType) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createPropertyKind__SWIG_1(swigCPtr, this, guid, title, namingSystem, uom.swigValue(), com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind.getCPtr(parentPropType), parentPropType);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.CommentProperty createCommentProperty(com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation rep, String guid, String title, long dimension, resqml2__IndexableElements attachmentKind, resqml2__ResqmlPropertyKind energisticsPropertyKind) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createCommentProperty__SWIG_0(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(rep), rep, guid, title, dimension, attachmentKind.swigValue(), energisticsPropertyKind.swigValue());
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.CommentProperty(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.CommentProperty createCommentProperty(com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation rep, String guid, String title, long dimension, resqml2__IndexableElements attachmentKind, com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind localPropType) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createCommentProperty__SWIG_1(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(rep), rep, guid, title, dimension, attachmentKind.swigValue(), com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind.getCPtr(localPropType), localPropType);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.CommentProperty(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.ContinuousProperty createContinuousProperty(com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation rep, String guid, String title, long dimension, resqml2__IndexableElements attachmentKind, resqml2__ResqmlUom uom, resqml2__ResqmlPropertyKind energisticsPropertyKind) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createContinuousProperty__SWIG_0(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(rep), rep, guid, title, dimension, attachmentKind.swigValue(), uom.swigValue(), energisticsPropertyKind.swigValue());
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.ContinuousProperty(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.ContinuousProperty createContinuousProperty(com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation rep, String guid, String title, long dimension, resqml2__IndexableElements attachmentKind, resqml2__ResqmlUom uom, com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind localPropType) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createContinuousProperty__SWIG_1(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(rep), rep, guid, title, dimension, attachmentKind.swigValue(), uom.swigValue(), com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind.getCPtr(localPropType), localPropType);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.ContinuousProperty(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.DiscreteProperty createDiscreteProperty(com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation rep, String guid, String title, long dimension, resqml2__IndexableElements attachmentKind, resqml2__ResqmlPropertyKind energisticsPropertyKind) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createDiscreteProperty__SWIG_0(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(rep), rep, guid, title, dimension, attachmentKind.swigValue(), energisticsPropertyKind.swigValue());
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.DiscreteProperty(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.DiscreteProperty createDiscreteProperty(com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation rep, String guid, String title, long dimension, resqml2__IndexableElements attachmentKind, com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind localPropType) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createDiscreteProperty__SWIG_1(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(rep), rep, guid, title, dimension, attachmentKind.swigValue(), com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind.getCPtr(localPropType), localPropType);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.DiscreteProperty(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.CategoricalProperty createCategoricalProperty(com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation rep, String guid, String title, long dimension, resqml2__IndexableElements attachmentKind, com.f2i.energisticsStandardsApi.resqml2_0.StringTableLookup strLookup, resqml2__ResqmlPropertyKind energisticsPropertyKind) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createCategoricalProperty__SWIG_0(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(rep), rep, guid, title, dimension, attachmentKind.swigValue(), com.f2i.energisticsStandardsApi.resqml2_0.StringTableLookup.getCPtr(strLookup), strLookup, energisticsPropertyKind.swigValue());
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.CategoricalProperty(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.resqml2_0.CategoricalProperty createCategoricalProperty(com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation rep, String guid, String title, long dimension, resqml2__IndexableElements attachmentKind, com.f2i.energisticsStandardsApi.resqml2_0.StringTableLookup strLookup, com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind localPropType) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createCategoricalProperty__SWIG_1(swigCPtr, this, com.f2i.energisticsStandardsApi.resqml2_0.AbstractRepresentation.getCPtr(rep), rep, guid, title, dimension, attachmentKind.swigValue(), com.f2i.energisticsStandardsApi.resqml2_0.StringTableLookup.getCPtr(strLookup), strLookup, com.f2i.energisticsStandardsApi.resqml2_0.PropertyKind.getCPtr(localPropType), localPropType);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.resqml2_0.CategoricalProperty(cPtr, false);
  }

  public TrajectoryVector getWitsmlTrajectorySet() {
    return new TrajectoryVector(com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_getWitsmlTrajectorySet(swigCPtr, this), true);
  }

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.Well createWell(String guid, String title, String timeZone) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createWell__SWIG_0(swigCPtr, this, guid, title, timeZone);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.witsml1_4_1_1.Well(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.Well createWell(String guid, String title, String timeZone, String operator_, witsml1__WellStatus statusWell, witsml1__WellPurpose purposeWell, witsml1__WellFluid fluidWell, witsml1__WellDirection directionWell, long dTimSpud, String sourceName, long dTimCreation, long dTimLastChange, String comments) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createWell__SWIG_1(swigCPtr, this, guid, title, timeZone, operator_, statusWell.swigValue(), purposeWell.swigValue(), fluidWell.swigValue(), directionWell.swigValue(), dTimSpud, sourceName, dTimCreation, dTimLastChange, comments);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.witsml1_4_1_1.Well(cPtr, false);
  }

  public com.f2i.energisticsStandardsApi.witsml1_4_1_1.CoordinateReferenceSystem createCoordinateReferenceSystem(String guid, String title, String namingSystem, String code, String sourceName, long dTimCreation, long dTimLastChange, String comments) {
    long cPtr = com.f2i.energisticsStandardsApi.energisticsApiJNI.common_EpcDocument_createCoordinateReferenceSystem(swigCPtr, this, guid, title, namingSystem, code, sourceName, dTimCreation, dTimLastChange, comments);
    return (cPtr == 0) ? null : new com.f2i.energisticsStandardsApi.witsml1_4_1_1.CoordinateReferenceSystem(cPtr, false);
  }

}
